const [formData, setFormData] = useState({
  name: "",
  projectDescription: "",
  country: null,
  location: null,
  locationFlag: false,
  filteredLocations: [],
  currencyName: null,
  loanType: null,
  minLoanAmt: "",
  maxLoanAmt: "",
  flatInterestRate: "",
  interestRatePeriod: "",
  interestPeriodUnit: null,
  downRepaymentGracePeriod: "",
  emiRepaymentGracePeriod: "",//graceForEmis
  loanGracePeriod: "",//loanGrace
  rollOverGracePeriod: "",//rollOverP
  rollOverPenaltyFactor: "",//rollOverF
  rollOverPenaltyFee: "",
  rollOverInterestRate: "",//rollOverIR
  lateEmiPenaltyFactor: "",//lateEMIPenalty
  maxPaymetAttemps: "",//maxPaymentAttempt
  rollOverEquation: "",
  startDate: startDate,
  endDate: "",
  lateRepaymentPenalty: "",
  earlyRepaymentDiscount: "",
  tclAmount: 0,
  minLoanOperator: "",
  minLoanAmount: 0,
  maxLoanOperator: "",
  maxLoanAmount: 0,
  tclOperator: "",
  minInstallmentsOperator: "",
  minInstallmentsAmount: 0,
  maxInstallmentsOperator: "",
  maxInstallmentsAmount: 0,
  serviceFee: "",
  calculateInterest: false,//calInterest
  hasEarlyLateRepayment: false,//earlyPay
  hasDownPayment: true,//hasDownPayPer
  managementFee: "",
  tclIncludeFee: true,//tclFee
  tclIncludeInterest: true,//tclInterest
  openLoanOperator: "",
  openLoanAmount: 0,
  vatFee: "",
  client: "DarwinClient",
});


  // "tclRef": "string" ??
  // "maxPaymetAttemps"  make it "maxPaymentAttempts" correct it
  // "clientIds" -> "client"  ?? ambiguity
  // rollOverPenaltyFee is not in API
  // DownPayment checkbox or input



const abc = {
  "name": "Subham Jain",
  "projectDescription": "jain",
  "country": "United States",
  "location": "Alabama",
  "locationFlag": false,
  "filteredLocations": [
      {
          "value": "Alabama",
          "label": "Alabama"
      },
      {
          "value": "Alaska",
          "label": "Alaska"
      },
      {
          "value": "Arizona",
          "label": "Arizona"
      },
      {
          "value": "Arkansas",
          "label": "Arkansas"
      },
      {
          "value": "California",
          "label": "California"
      },
      {
          "value": "Colorado",
          "label": "Colorado"
      },
      {
          "value": "Connecticut",
          "label": "Connecticut"
      },
      {
          "value": "Delaware",
          "label": "Delaware"
      },
      {
          "value": "Florida",
          "label": "Florida"
      },
      {
          "value": "Georgia",
          "label": "Georgia"
      },
      {
          "value": "Hawaii",
          "label": "Hawaii"
      },
      {
          "value": "Idaho",
          "label": "Idaho"
      },
      {
          "value": "Illinois",
          "label": "Illinois"
      },
      {
          "value": "Indiana",
          "label": "Indiana"
      },
      {
          "value": "Iowa",
          "label": "Iowa"
      },
      {
          "value": "Kansas",
          "label": "Kansas"
      },
      {
          "value": "Kentucky",
          "label": "Kentucky"
      },
      {
          "value": "Louisiana",
          "label": "Louisiana"
      },
      {
          "value": "Maine",
          "label": "Maine"
      },
      {
          "value": "Maryland",
          "label": "Maryland"
      },
      {
          "value": "Massachusetts",
          "label": "Massachusetts"
      },
      {
          "value": "Michigan",
          "label": "Michigan"
      },
      {
          "value": "Minnesota",
          "label": "Minnesota"
      },
      {
          "value": "Mississippi",
          "label": "Mississippi"
      },
      {
          "value": "Missouri",
          "label": "Missouri"
      },
      {
          "value": "Montana",
          "label": "Montana"
      },
      {
          "value": "Nebraska",
          "label": "Nebraska"
      },
      {
          "value": "Nevada",
          "label": "Nevada"
      },
      {
          "value": "New Hampshire",
          "label": "New Hampshire"
      },
      {
          "value": "New Jersey",
          "label": "New Jersey"
      },
      {
          "value": "New Mexico",
          "label": "New Mexico"
      },
      {
          "value": "New York",
          "label": "New York"
      },
      {
          "value": "North Carolina",
          "label": "North Carolina"
      },
      {
          "value": "North Dakota",
          "label": "North Dakota"
      },
      {
          "value": "Ohio",
          "label": "Ohio"
      },
      {
          "value": "Oklahoma",
          "label": "Oklahoma"
      },
      {
          "value": "Oregon",
          "label": "Oregon"
      },
      {
          "value": "Pennsylvania",
          "label": "Pennsylvania"
      },
      {
          "value": "Rhode Island",
          "label": "Rhode Island"
      },
      {
          "value": "South Carolina",
          "label": "South Carolina"
      },
      {
          "value": "South Dakota",
          "label": "South Dakota"
      },
      {
          "value": "Tennessee",
          "label": "Tennessee"
      },
      {
          "value": "Texas",
          "label": "Texas"
      },
      {
          "value": "Utah",
          "label": "Utah"
      },
      {
          "value": "Vermont",
          "label": "Vermont"
      },
      {
          "value": "Virginia",
          "label": "Virginia"
      },
      {
          "value": "Washington",
          "label": "Washington"
      },
      {
          "value": "West Virginia",
          "label": "West Virginia"
      },
      {
          "value": "Wisconsin",
          "label": "Wisconsin"
      },
      {
          "value": "Wyoming",
          "label": "Wyoming"
      }
  ],
  "currencyName": "USD",
  "loanType": "asset",
  "minLoanAmt": "",
  "maxLoanAmt": "",
  "flatInterestRate": "6",
  "interestRatePeriod": "30",
  "interestPeriodUnit": "Monthly",
  "downRepaymentGracePeriod": "30",
  "emiRepaymentGracePeriod": "30",
  "loanGracePeriod": "30",
  "rollOverGracePeriod": "30",
  "rollOverPenaltyFactor": "0",
  "rollOverPenaltyFee": "12345",
  "rollOverInterestRate": "6",
  "lateEmiPenaltyFactor": "6",
  "maxPaymetAttemps": "2",
  "rollOverEquation": "",
  "startDate": "2024-07-02 00:00:00",
  "endDate": "2024-07-04 00:00:00",
  "lateRepaymentPenalty": "10",
  "tclAmount": "10",
  "minLoanOperator": "==",
  "minLoanAmount": "10",
  "maxLoanOperator": "==",
  "maxLoanAmount": "10",
  "earlyRepaymentDiscount": "0",
  "tclOperator": "==",
  "minInstallmentsOperator": "==",
  "minInstallmentsAmount": "10",
  "maxInstallmentsOperator": "==",
  "maxInstallmentsAmount": "10",
  "serviceFee": "0",
  "calculateInterest": false,
  "hasEarlyLateRepayment": true,
  "hasDownPayment": "0",
  "managementFee": "14",
  "tclIncludeFee": true,
  "tclIncludeInterest": true,
  "openLoanOperator": "==",
  "openLoanAmount": "10",
  "vatFee": "12",
  "client": "DarwinClient",
  "projectTimeZone": "GMT-180",
  "paymentOption": [
      "mobile wallet",
      "top up",
      "credit card"
  ],
  "bearers": [
      "SMS",
      "USSD"
  ],
  "criteria": "tcl undefined 10 and loanAmount undefined 10 and loanAmount undefined 10 and numberOfInstallments undefined 10 and numberOfInstallments undefined 10 and freqCap undefined 10"
}

export const locationOptions = {
  Zambia: [
    "Lusaka",
    "Ndola",
    "Kitwe",
    "Kabwe",
    "Chingola",
    "Mufulira",
    "Livingstone",
    "Luanshya",
    "Kasama",
    "Chipata",
    "Kalulushi",
    "Mazabuka",
    "Chililabombwe",
    "Mongu",
    "Kafue",
    "Choma",
    "Kasama",
    "Kapiri Mposhi",
    "Kawambwa",
    "Kansanshi",
    "Mbala",
    "Chambishi",
    "Monze",
    "Serenje",
    "Mpika",
    "Sesheke",
    "Mansa",
    "Samfya",
    "Petauke",
    "Chinsali",
    "Isoka",
    "Choma",
    "Kalabo",
    "Kasempa",
    "Lundazi",
    "Mwinilunga",
    "Siavonga",
    "Chirundu",
  ],
  Venezuela: [
    "Caracas", "Maracaibo", "Valencia", "Barquisimeto", "Maracay",
    "Ciudad Guayana", "San Cristóbal", "Maturín", "Barcelona",
    "Puerto La Cruz", "Los Teques", "Carúpano", "Guarenas", "Barinas",
    "Cabimas", "Ciudad Bolívar", "Cumaná", "Mérida", "Guanare",
    "Punto Fijo", "Puerto Cabello", "Guacara", "Los Guayos",
    "San Fernando de Apure", "Santa Teresa del Tuy", "Cumana",
    "Charallave", "Tariba", "Coro", "Trujillo", "La Victoria",
    "Valera", "Acarigua", "El Tigre", "Palo Negro", "Santa Rita",
    "Guatire", "San Juan de los Morros", "Machiques", "San Felipe",
    "El Limón", "Upata", "El Vigía"
  ],

  Turkey: [
    "Istanbul", "Ankara", "Izmir", "Bursa", "Antalya", "Adana",
    "Konya", "Gaziantep", "Diyarbakir", "Mersin", "Kayseri",
    "Eskisehir", "Samsun", "Denizli", "Sanliurfa", "Malatya",
    "Sakarya", "Kahramanmaras", "Erzurum", "Van", "Batman",
    "Elazig", "Sivas", "Manisa", "Balikesir", "Adiyaman",
    "Osmaniye", "Isparta", "Aydin", "Trabzon", "Ordu",
    "Corum", "Aksaray", "Erzincan", "Kutahya", "Siirt",
    "Igdir", "Kastamonu", "Bolu", "Sinop", "Zonguldak",
    "Yozgat", "Rize", "Tokat", "Nigde", "Bilecik",
    "Karaman", "Kirikkale", "Yalova", "Edirne", "Giresun",
    "Nevsehir", "Agri", "Amasya", "Mus", "Artvin",
    "Bayburt", "Kars", "Kirklareli", "Bitlis", "Sirnak",
    "Bingol", "Tunceli", "Duzce"
  ],

  "Trinidad and Tobago": [
    "Port of Spain", "San Fernando", "Chaguanas", "Arima", "Point Fortin",
    "Scarborough", "Tunapuna", "Sangre Grande", "Princes Town", "Rio Claro",
    "Penal", "Siparia", "Couva", "Arouca", "Saint Augustine",
    "Mucurapo", "Petit Valley", "Mara Valley", "Toco", "Carenage"
  ],

  Thailand: [
    "Bangkok", "Nonthaburi", "Samut Prakan", "Chiang Mai", "Udon Thani",
    "Nakhon Ratchasima", "Hat Yai", "Pak Kret", "Si Racha", "Phuket",
    "Chaophraya Surasak", "Nakhon Si Thammarat", "Bang Yai", "Khon Kaen",
    "Pak Chong", "Ubon Ratchathani", "Surat Thani", "Nakhon Pathom",
    "Chiang Rai", "Rayong", "Phra Pradaeng", "Sakhon Nakhon",
    "Maha Sarakham", "Ratchaburi", "Trang", "Phitsanulok",
    "Ban Lam Luk Ka", "Samut Sakhon", "Chachoengsao", "Clementi",
    "Bang Sao Thong", "Yala", "Roi Et", "Phra Nakhon Si Ayutthaya",
    "Phetchabun", "Chon Buri", "Songkhla", "Bang Lamung", "Bang Kruai",
    "Pattaya", "Pattani", "Lop Buri", "Ban Phai", "Ko Samui",
    "Sattahip", "Kanchanaburi", "Krathum Baen", "Surin", "Uttaradit"
  ],

  Taiwan: [
    "Taipei", "New Taipei City", "Kaohsiung", "Taichung", "Tainan",
    "Taoyuan City", "Hsinchu", "Keelung", "Chiayi", "Changhua City",
    "Pingtung City", "Yilan City", "Zhubei", "Douliu", "Nantou City",
    "Taitung City", "Hualien City", "Miaoli City", "Yilan", "Puzi City",
    "Jincheng", "Magong", "Changhua", "Puli", "Hualien", "Toufen",
    "Chiayi City", "Nantou", "Taitung", "Penghu", "Kinmen", "Lienchiang"
  ],

  Switzerland: [
    "Zurich", "Geneva", "Basel", "Lausanne", "Bern",
    "Winterthur", "Lucerne", "St. Gallen", "Lugano", "Biel/Bienne",
    "Thun", "Köniz", "La Chaux-de-Fonds", "Schaffhausen", "Fribourg",
    "Chur", "Neuchâtel", "Vernier", "Uster", "Sion", "Emmen",
    "Thurgau", "Zug", "Yverdon-les-Bains", "Schlieren", "Dübendorf",
    "Baar", "Kriens", "Rapperswil-Jona", "Allschwil", "Bellinzona",
    "Wil", "Renens", "Nyon", "Muttenz", "Vevey", "Pully",
    "Zürich (Kreis 11) / Oerlikon", "Riehen", "Volketswil",
    "Seen (Kreis 3)", "Zürich (Kreis 2) / Wollishofen", "Bülach"
  ],

  Sweden: [
    "Stockholm", "Gothenburg", "Malmö", "Uppsala", "Västerås",
    "Örebro", "Linköping", "Helsingborg", "Jönköping", "Norrköping",
    "Lund", "Umeå", "Gävle", "Borås", "Södertälje", "Växjö",
    "Halmstad", "Karlstad", "Eskilstuna", "Täby", "Sollentuna",
    "Tumba", "Trollhättan", "Borlänge", "Upplands Väsby", "Falun",
    "Östersund", "Sundsvall", "Trelleborg", "Luleå", "Huddinge",
    "Kungsbacka", "Kristianstad", "Kalmar", "Skövde", "Karlskrona",
    "Varberg", "Hässleholm", "Nyköping", "Karlskoga"
  ],

  Sudan: [
    "Khartoum", "Omdurman", "Port Sudan", "Kassala", "El Obeid",
    "Kosti", "Wad Madani", "Nyala", "Al Ubayyid", "Kūstī",
    "Rabak", "Sennar", "Gedaref", "Atbara", "Ad-Damazin",
    "Kadugli", "Zalingei", "Geneina", "Umm Ruwaba"
  ],
  Spain: [
    "Madrid",
    "Barcelona",
    "Valencia",
    "Seville",
    "Zaragoza",
    "Málaga",
    "Murcia",
    "Palma",
    "Las Palmas de Gran Canaria",
    "Bilbao",
    "Alicante",
    "Córdoba",
    "Valladolid",
    "Vigo",
    "Gijón",
    "L'Hospitalet de Llobregat",
    "A Coruña",
    "Vitoria-Gasteiz",
    "Granada",
    "Elche",
    "Oviedo",
    "Badalona",
    "Terrassa",
    "Cartagena",
    "Jerez de la Frontera",
    "Sabadell",
    "Móstoles",
    "Santa Cruz de Tenerife",
    "Alcalá de Henares",
    "Fuenlabrada",
    "Almería",
    "Pamplona",
    "Leganés",
    "San Sebastián",
    "Getafe",
    "Burgos",
    "Huelva",
    "Salamanca",
    "Albacete",
    "Logroño",
    "Badajoz",
    "Huesca",
    "Tarragona",
    "León",
    "Cádiz",
    "Jaén",
    "Ourense",
    "Mérida",
    "Ávila",
    "Segovia",
    "Cuenca",
    "Lleida",
    "Girona",
    "Toledo",
    "Soria",
    "Melilla",
    "Ceuta"
  ],
  "South Africa": [
    "Johannesburg",
    "Cape Town",
    "Durban",
    "Pretoria",
    "Port Elizabeth",
    "Bloemfontein",
    "East London",
    "Polokwane",
    "Nelspruit",
    "Kimberley",
    "Upington",
    "Pietermaritzburg",
    "Mthatha",
    "Rustenburg",
    "George",
    "Witbank",
    "Mafikeng",
    "Vryheid",
    "Potchefstroom",
    "Welkom",
    "Umtata",
    "Grahamstown",
    "Klerksdorp",
    "Vereeniging",
    "Sasolburg",
    "Queenstown",
    "Bethlehem",
    "Ladysmith",
    "Richards Bay",
    "Mossel Bay",
    "Kroonstad",
    "Knysna",
    "Krugersdorp",
    "Carletonville",
    "Thohoyandou",
    "Graaff-Reinet",
    "Piet Retief",
    "Standerton",
    "Boksburg",
    "Vryburg",
    "Komatipoort",
    "Middelburg",
    "Hermanus",
    "Aliwal North",
    "KwaDukuza",
    "Lichtenburg",
    "Moorreesburg",
    "Mthatha",
    "Plettenberg Bay",
    "Senekal",
    "Thaba Nchu"
  ],
  Slovakia: [
    "Bratislava",
    "Košice",
    "Prešov",
    "Žilina",
    "Banská Bystrica",
    "Nitra",
    "Trnava",
    "Trenčín",
    "Martin",
    "Poprad",
    "Prievidza",
    "Zvolen",
    "Žiar nad Hronom",
    "Michalovce",
    "Spišská Nová Ves",
    "Komárno",
    "Levice",
    "Humenné",
    "Bardejov",
    "Liptovský Mikuláš",
    "Rimavská Sobota",
    "Dunajská Streda",
    "Veľký Krtíš",
    "Senica",
    "Považská Bystrica",
    "Galanta",
    "Nové Zámky",
    "Šaľa",
    "Brezno",
    "Snina",
    "Skalica",
    "Štúrovo",
    "Kežmarok",
    "Detva",
    "Medzilaborce",
    "Svidník",
    "Kysucké Nové Mesto",
    "Hlohovec",
    "Partizánske",
    "Dolný Kubín",
    "Púchov",
    "Žarnovica",
    "Ilava",
    "Levoča",
    "Stropkov",
    "Stará Ľubovňa",
    "Polta"
  ],
  SA: [
    "Riyadh",
    "Jeddah",
    "Mecca",
    "Medina",
    "Dammam",
    "Tabuk",
    "Al-Khobar",
    "Jubail",
    "Abha",
    "Buraidah",
    "Najran",
    "Taif",
    "Al Bahah",
    "Hail",
    "Khamis Mushait",
    "Al Qunfudhah",
    "Al Kharj",
    "Al Majma'ah",
    "Al-Hofuf",
    "Al-Mubarraz",
    "Arar",
    "Sakakah",
    "Jizan",
    "Rafha",
    "Dhahran",
    "Yanbu",
    "Al-Bukayriyah",
    "Al-Dawadmi",
    "Al-Diriyah",
    "Badr",
    "Baljurashi",
    "Bisha",
    "Dumat Al-Jandal",
    "Dubaiyyah",
    "Hafr Al-Batin",
    "Khobar",
    "Makkah",
    "Najaf",
    "Onaizah",
    "Qatif",
    "Qunfudhah",
    "Sabya",
    "Salwa",
    "Sulayyil",
    "Turaif",
    "Ula",
    "Unaizah",
    "Yanbu' al Bahr",
    "Zulfi"
  ],
  Singapore: [
    "Singapore",
    "Jurong",
    "Woodlands",
    "Tampines",
    "Ang Mo Kio",
    "Hougang",
    "Punggol",
    "Bedok",
    "Choa Chu Kang",
    "Bukit Batok",
    "Sengkang",
    "Yishun",
    "Pasir Ris",
    "Serangoon",
    "Clementi",
    "Bukit Merah",
    "Bukit Panjang",
    "Toa Payoh",
    "Queenstown",
    "Sembawang",
    "Marine Parade",
    "Central Area",
    "Bishan",
    "Geylang",
    "Kallang",
    "Bukit Timah",
    "Novena",
    "Outram",
    "Rochor",
    "River Valley",
    "Newton",
    "Orchard",
    "Tanglin",
    "Singapore River",
    "Downtown Core",
    "Marina East",
    "Marina South",
    "Marine Parade",
    "Straits View",
    "Marina South",
    "Marina East",
    "Bukit Merah",
    "Southern Islands"
  ],
  Russia: [
    "Moscow",
    "Saint Petersburg",
    "Novosibirsk",
    "Yekaterinburg",
    "Nizhny Novgorod",
    "Kazan",
    "Chelyabinsk",
    "Omsk",
    "Samara",
    "Rostov-on-Don",
    "Ufa",
    "Krasnoyarsk",
    "Voronezh",
    "Perm",
    "Volgograd",
    "Krasnodar",
    "Saratov",
    "Tyumen",
    "Tolyatti",
    "Izhevsk",
    "Barnaul",
    "Ulyanovsk",
    "Irkutsk",
    "Yaroslavl",
    "Khabarovsk",
    "Vladivostok",
    "Makhachkala",
    "Tomsk",
    "Orenburg",
    "Kemerovo",
    "Novokuznetsk",
    "Ryazan",
    "Astrakhan",
    "Penza",
    "Naberezhnye Chelny",
    "Lipetsk",
    "Tula",
    "Kirov",
    "Cheboksary",
    "Kaliningrad",
    "Bryansk",
    "Ivanovo",
    "Magnitogorsk",
    "Belgorod",
    "Surgut"
  ],
  Romania: [
    "Bucharest",
    "Cluj-Napoca",
    "Timișoara",
    "Iași",
    "Constanța",
    "Craiova",
    "Brașov",
    "Galați",
    "Ploiești",
    "Oradea",
    "Brăila",
    "Arad",
    "Pitești",
    "Sibiu",
    "Bacău",
    "Târgu Mureș",
    "Baia Mare",
    "Buzău",
    "Botoșani"
  ],
  Portugal: [
    "Lisbon",
    "Porto",
    "Vila Nova de Gaia",
    "Amadora",
    "Braga",
    "Setúbal",
    "Coimbra",
    "Queluz",
    "Funchal",
    "Cacém",
    "Vila Nova de Famalicão",
    "Viseu",
    "Agualva-Cacém",
    "Rio Tinto",
    "Odivelas",
    "Aveiro",
    "Barreiro",
    "Póvoa de Varzim",
    "Vila Franca de Xira",
    "Matosinhos",
    "Maia",
    "Gondomar",
    "Ermesinde",
    "Felgueiras",
    "Castelo Branco",
    "Bragança",
    "Portimão",
    "Leiria",
    "Ponte de Lima",
    "Faro",
    "Santa Maria da Feira",
    "Évora",
    "Guarda",
    "Almada",
    "Cascais",
    "Viana do Castelo",
    "Machico",
    "Montijo",
    "Beja",
    "Loures",
    "Ribeira Brava",
    "Águeda",
    "Santarém",
    "Ponta Delgada",
    "Oliveira de Azeméis",
    "Estoril",
    "Penafiel"
  ],
  Poland: [
    "Warsaw",
    "Kraków",
    "Łódź",
    "Wrocław",
    "Poznań",
    "Gdańsk",
    "Szczecin",
    "Bydgoszcz",
    "Lublin",
    "Białystok",
    "Katowice",
    "Gdynia",
    "Częstochowa",
    "Radom",
    "Sosnowiec",
    "Toruń",
    "Kielce",
    "Rzeszów",
    "Gliwice",
    "Zabrze",
    "Olsztyn",
    "Bielsko-Biała",
    "Bytom",
    "Zielona Góra",
    "Rybnik",
    "Ruda Śląska",
    "Tychy",
    "Gorzów Wielkopolski",
    "Dąbrowa Górnicza",
    "Płock",
    "Elbląg",
    "Opole",
    "Wałbrzych",
    "Głogów",
    "Słupsk",
    "Jastrzębie-Zdrój",
    "Jaworzno",
    "Jelenia Góra",
    "Nowy Sącz",
    "Konin",
    "Piotrków Trybunalski",
    "Tarnów",
    "Przemyśl",
    "Stalowa Wola",
    "Mysłowice"
  ],
  Philippines: [
    "Manila",
    "Quezon City",
    "Caloocan",
    "Davao City",
    "Cebu City",
    "Antipolo",
    "Pasig",
    "Taguig",
    "Cagayan de Oro",
    "Parañaque",
    "Makati",
    "Bacolod",
    "Muntinlupa",
    "Pasay",
    "Dasmariñas",
    "Valenzuela",
    "Las Piñas",
    "General Santos",
    "San Jose del Monte",
    "Bacoor",
    "Iloilo City",
    "Dagupan",
    "Mandaue",
    "Baguio",
    "Tarlac City",
    "Lapu-Lapu",
    "Butuan",
    "Imus",
    "Angeles",
    "Naga",
    "Cavite City",
    "Marikina",
    "San Pedro",
    "Mabalacat",
    "San Fernando",
    "Lipa",
    "Navotas",
    "Lucena",
    "Tacloban",
    "Olongapo",
    "Ormoc",
    "Calamba",
    "Malolos",
    "Panabo",
    "Digos",
    "Koronadal",
    "Santiago",
    "Toledo",
    "Iriga",
    "Roxas",
    "Tabaco"
  ],
  Pakistan: [
    "Karachi",
    "Lahore",
    "Faisalabad",
    "Rawalpindi",
    "Multan",
    "Gujranwala",
    "Islamabad",
    "Quetta",
    "Peshawar",
    "Sargodha",
    "Sialkot",
    "Bahawalpur",
    "Sukkur",
    "Jhang",
    "Sheikhupura",
    "Larkana",
    "Gujrat",
    "Mardan",
    "Kasur",
    "Rahim Yar Khan",
    "Sahiwal",
    "Okara",
    "Wah Cantonment",
    "Dera Ghazi Khan",
    "Mirpur Khas",
    "Nawabshah",
    "Buner",
    "Khanewal",
    "Hafizabad",
    "Kohat",
    "Jacobabad",
    "Shikarpur",
    "Muzaffargarh",
    "Khanpur",
    "Gojra",
    "Bahawalnagar",
    "Muridke",
    "Pakpattan",
    "Abottabad",
    "Tando Allahyar",
    "Jhelum",
    "Kasur",
    "Dera Ismail Khan",
    "Chiniot",
    "Charsadda"
  ],
  Norway: [
    "Oslo",
    "Bergen",
    "Trondheim",
    "Stavanger",
    "Drammen",
    "Fredrikstad",
    "Kristiansand",
    "Sandnes",
    "Tromsø",
    "Sarpsborg",
    "Skien",
    "Ålesund",
    "Sandefjord",
    "Haugesund",
    "Tønsberg",
    "Moss",
    "Porsgrunn",
    "Bodø",
    "Arendal",
    "Hamar",
    "Ytrebygda",
    "Halden",
    "Larvik",
    "Askøy",
    "Kongsberg",
    "Molde",
    "Harstad",
    "Horten",
    "Lillehammer",
    "Gjøvik",
    "Mandal",
    "Narvik",
    "Kristiansund",
    "Tromsdalen",
    "Mosjøen",
    "Sarpsborg",
    "Leirvik",
    "Ørsta",
    "Grimstad",
    "Notodden",
    "Bryne",
    "Vennesla",
    "Ålgård",
    "Elverum"
  ],
  Mexico: [
    "Mexico City",
    "Guadalajara",
    "Monterrey",
    "Puebla",
    "Tijuana",
    "Ciudad Juárez",
    "León",
    "Zapopan",
    "Guadalupe",
    "Hermosillo",
    "Querétaro",
    "Toluca",
    "Mérida",
    "Aguascalientes",
    "San Luis Potosí",
    "Mexicali",
    "Culiacán",
    "Acapulco",
    "Chihuahua",
    "Tuxtla Gutiérrez",
    "Saltillo",
    "Cancún",
    "Morelia",
    "Reynosa",
    "Torreón",
    "Tlaquepaque",
    "Durango",
    "Veracruz",
    "Tampico",
    "Cuernavaca",
    "Xalapa",
    "Tepic",
    "Ciudad Victoria",
    "Oaxaca",
    "Campeche",
    "Tuxtla",
    "La Paz",
    "Colima",
    "Chilpancingo",
    "Tlaxcala",
    "Ciudad Victoria",
    "Pachuca",
    "Ciudad del Carmen",
    "Ciudad Madero",
    "Nuevo Laredo",
    "San Francisco de Campeche",
    "Matamoros"
  ],
  Malaysia: [
    "Kuala Lumpur",
    "George Town",
    "Ipoh",
    "Kuching",
    "Johor Bahru",
    "Kota Kinabalu",
    "Shah Alam",
    "Malacca City",
    "Alor Setar",
    "Miri",
    "Petaling Jaya",
    "Kuala Terengganu",
    "Seremban",
    "Kuantan",
    "Kota Bharu",
    "Sandakan",
    "Taiping",
    "Butterworth",
    "Sungai Petani",
    "Sibu",
    "Tawau",
    "Batu Pahat",
    "Raub",
    "Kluang",
    "Kangar",
    "Bintulu",
    "Temerloh",
    "Taiping",
    "Kuala Kangsar",
    "Kuala Langat",
    "Segamat",
    "Langkawi",
    "Teluk Intan",
    "Simpang Empat",
    "Kampar",
    "Kulim"
  ],
  Luxembourg:[
    "Luxembourg City", "Esch-sur-Alzette", "Differdange", "Dudelange", "Ettelbruck",
    "Diekirch", "Wiltz", "Echternach", "Rumelange", "Grevenmacher", "Remich",
    "Vianden", "Mersch", "Redange-sur-Attert", "Capellen", "Wiltz", "Schifflange",
    "Bettembourg", "Petange", "Strassen", "Bertrange", "Sanem", "Mondercange",
    "Mondorf-les-Bains", "Junglinster", "Remich", "Grosbous", "Steinsel", "Kehlen",
    "Steinfort", "Mamer", "Wormeldange", "Saeul", "Walferdange", "Schieren",
    "Kayl", "Weiler-la-Tour"
  ],
  Lebanon:[
    "Beirut", "Tripoli", "Sidon", "Tyre", "Byblos", "Jounieh", "Baabda", "Nabatieh",
    "Zahle", "Batroun", "Baalbek", "Zahleh", "Jbeil", "Saida", "Bint Jbeil", "Bekaa",
    "Marjayoun", "Aley", "Akkar", "Rashaya"
  ],
  "South Korea":[
    "Seoul", "Busan", "Incheon", "Daegu", "Daejeon", "Gwangju", "Ulsan", "Suwon",
    "Seongnam", "Goyang", "Bucheon", "Yongin", "Cheongju", "Ansan", "Jeonju",
    "Cheonan", "Gimhae", "Hwaseong", "Sacheon", "Gumi", "Gwacheon", "Iksan",
    "Pohang", "Suncheon", "Jeju", "Gangneung", "Chuncheon", "Yeosu", "Asan",
    "Gwangmyeong", "Naju", "Uijeongbu", "Anyang", "Changwon", "Sejong", "Mokpo",
    "Paju", "Andong", "Namyangju", "Yangsan", "Yangju", "Kimhae", "Seosan"
  ],
  Jordan:[
    "Amman", "Zarqa", "Irbid", "Salt", "Ar Ramtha", "Madaba", "Aqaba", "Jerash",
    "Karak", "Ma'an", "Tafilah", "Mafraq", "Sahab", "Al Quwaysimah", "Ajloun",
    "Al Husn", "At Tafilah", "Azraq", "Bayir", "Dhiban", "Fuheis", "Kofranjah",
    "Safawi", "Sakhrah", "Sama as Sarhan", "Umm as Summaq"
  ],
  Japan:[
    "Tokyo", "Yokohama", "Osaka", "Nagoya", "Sapporo", "Fukuoka", "Kobe", "Kyoto",
    "Kawasaki", "Saitama", "Hiroshima", "Sendai", "Kitakyushu", "Chiba", "Sakai",
    "Niigata", "Hamamatsu", "Okayama", "Sagamihara", "Kumamoto", "Kagoshima",
    "Funabashi", "Higashiosaka", "Hachioji", "Nerima", "Kurashiki", "Gifu", "Akita",
    "Miyazaki", "Toyota", "Maebashi", "Otsu", "Ichikawa", "Yokosuka", "Kakogawa",
    "Mito", "Matsudo", "Takamatsu", "Takasaki", "Yokkaichi", "Toyohashi", "Morioka",
    "Fukushima", "Nara", "Asahikawa", "Oita"
  ],
  Jamaica:[
    "Kingston", "Montego Bay", "Spanish Town", "Portmore", "May Pen", "Mandeville",
    "Old Harbour", "Linstead", "Half Way Tree", "Savanna-la-Mar", "Saint Ann's Bay",
    "Port Antonio", "Morant Bay", "Stony Hill", "Santa Cruz", "Old Harbour Bay",
    "Ocho Rios", "Port Maria", "Falmouth", "Yallahs", "Bog Walk"
  ],
  Italy:[
    "Rome", "Milan", "Naples", "Turin", "Palermo", "Genoa", "Bologna", "Florence",
    "Bari", "Catania", "Venice", "Verona", "Messina", "Padua", "Trieste", "Brescia",
    "Taranto", "Prato", "Modena", "Reggio Calabria", "Reggio Emilia", "Perugia",
    "Ravenna", "Livorno", "Cagliari", "Foggia", "Rimini", "Salerno", "Ferrara",
    "Sassari", "Latina", "Giugliano in Campania", "Monza", "Syracuse", "Bergamo",
    "Pescara", "Trento", "Forlì", "Vicenza", "Terni", "Bolzano", "Novara", "Piacenza",
    "Ancona", "Arezzo", "Udine"
  ],
  Israel:[
    "Jerusalem", "Tel Aviv", "Haifa", "Rishon LeZion", "Petah Tikva", "Ashdod",
    "Netanya", "Beer Sheva", "Holon", "Bnei Brak", "Ramat Gan", "Bat Yam", "Rehovot",
    "Herzliya", "Kfar Saba", "Modi'in-Maccabim-Re'ut", "Nazareth", "Beit Shemesh",
    "Lod", "Ashkelon", "Nahariya", "Hadera", "Ramla", "Kiryat Gat", "Lahavim",
    "Modi'in Illit", "Qiryat Shemona", "Dimona", "Eilat", "Tiberias", "Safed",
    "Yavne", "Sderot", "Hod HaSharon", "Ra'anana", "Nof HaGalil", "Giv'atayim",
    "Qalansawe", "Rosh HaAyin", "Kiryat Ata", "Judea and Samaria Area",
    "West Jerusalem", "Afula", "Kiryat Bialik", "Kiryat Motzkin", "Tamra"
  ],
  Ireland:[
    "Dublin", "Cork", "Galway", "Limerick", "Waterford", "Drogheda", "Dundalk", "Bray",
    "Swords", "Navan", "Ennis", "Kilkenny", "Tralee", "Carlow", "Newbridge", "Naas",
    "Athlone", "Mullingar", "Wexford", "Letterkenny", "Sligo", "Clonmel", "Greystones",
    "Malahide", "Leixlip", "Carrigaline", "Castlebar", "Midleton", "Mallow", "Ballina",
    "Enniscorthy", "Shannon", "Arklow", "Tullamore", "Tramore", "New Ross", "Thurles",
    "Youghal", "Portlaoise"
  ],
  Indonesia: [
    "Jakarta",
    "Surabaya",
    "Bandung",
    "Medan",
    "Semarang",
    "Makassar",
    "Palembang",
    "Tangerang",
    "Depok",
    "Batam",
    "Bekasi",
    "Surakarta",
    "Padang",
    "Bandar Lampung",
    "Denpasar",
    "Bogor",
    "Pekanbaru",
    "Malang",
    "Yogyakarta",
    "Samarinda",
    "Tarakan",
    "Manado",
    "Balikpapan",
    "Jambi",
    "Cimahi",
    "Pontianak",
    "Banjarmasin",
    "Banda Aceh",
    "Tegal",
    "Percut Sei Tuan",
    "Binjai",
    "Padangsidempuan",
    "Tanjung Balai",
    "Pekalongan",
    "Cirebon",
    "Bukittinggi",
    "Mataram",
    "Probolinggo",
    "Kupang",
    "Sukabumi",
    "Purwokerto",
    "Singkawang",
    "Serang",
    "Tasikmalaya",
    "Pematangsiantar",
    "Palu",
    "Bengkulu",
    "Langsa",
    "Mojokerto",
    "Madiun",
    "Kediri",
    "Jayapura"
  ],
  Iceland: [
    "Reykjavik",
    "Kópavogur",
    "Hafnarfjörður",
    "Akureyri",
    "Keflavík",
    "Garðabær",
    "Mosfellsbær",
    "Árborg",
    "Akranes",
    "Selfoss",
    "Vestmannaeyjar",
    "Sauðárkrókur",
    "Fjarðabyggð",
    "Egilsstaðir",
    "Vík í Mýrdal",
    "Húsavík",
    "Borgarnes",
    "Ísafjörður",
    "Dalvík",
    "Grindavík",
    "Hveragerði",
    "Blönduós",
    "Sandgerði",
    "Stykkishólmur",
    "Seyðisfjörður",
    "Vogar",
    "Höfn í Hornafirði",
    "Seltjarnarnes",
    "Hafnir",
    "Hvanneyri",
    "Þorlákshöfn",
    "Reyðarfjörður",
    "Fáskrúðsfjörður",
    "Eskifjörður",
    "Bolungarvík",
    "Raufarhöfn",
    "Bíldudalur",
    "Djúpivogur",
    "Njarðvík"
  ],
  Hungary: [
    "Budapest",
    "Debrecen",
    "Szeged",
    "Miskolc",
    "Pécs",
    "Győr",
    "Nyíregyháza",
    "Kecskemét",
    "Székesfehérvár",
    "Szombathely",
    "Érd",
    "Tatabánya",
    "Sopron",
    "Kaposvár",
    "Veszprém",
    "Békéscsaba",
    "Zalaegerszeg",
    "Eger",
    "Nagykanizsa",
    "Dunaújváros",
    "Hódmezővásárhely",
    "Szekszárd",
    "Salgótarján",
    "Vác",
    "Gödöllő",
    "Szolnok",
    "Baja",
    "Hajdúböszörmény",
    "Kazincbarcika",
    "Orosháza",
    "Szentes",
    "Mosonmagyaróvár",
    "Pápa",
    "Várpalota",
    "Rákospalota"
  ],
  "Hong Kong": [
    "Central and Western",
    "Eastern",
    "Southern",
    "Wan Chai",
    "Sham Shui Po",
    "Kowloon City",
    "Kwun Tong",
    "Wong Tai Sin",
    "Yau Tsim Mong",
    "Islands",
    "Kwai Tsing",
    "North",
    "Sai Kung",
    "Sha Tin",
    "Tai Po",
    "Tsuen Wan",
    "Tuen Mun",
    "Yuen Long"
  ],
  Germany: [
    "Berlin",
    "Hamburg",
    "Munich",
    "Cologne",
    "Frankfurt",
    "Stuttgart",
    "Düsseldorf",
    "Dortmund",
    "Essen",
    "Leipzig",
    "Bremen",
    "Dresden",
    "Hanover",
    "Nuremberg",
    "Duisburg",
    "Bochum",
    "Wuppertal",
    "Bielefeld",
    "Bonn",
    "Münster",
    "Karlsruhe",
    "Mannheim",
    "Augsburg",
    "Wiesbaden",
    "Gelsenkirchen",
    "Mönchengladbach",
    "Braunschweig",
    "Chemnitz",
    "Kiel",
    "Aachen",
    "Halle",
    "Magdeburg",
    "Freiburg",
    "Krefeld",
    "Lübeck",
    "Oberhausen",
    "Erfurt",
    "Mainz",
    "Rostock",
    "Kassel",
    "Hagen",
    "Saarbrücken",
    "Hamm",
    "Potsdam",
    "Ludwigshafen",
    "Oldenburg",
    "Leverkusen"
  ],
  Greece: [
    "Athens",
    "Thessaloniki",
    "Patras",
    "Heraklion",
    "Larissa",
    "Volos",
    "Rhodes",
    "Ioannina",
    "Chania",
    "Chalcis",
    "Sparta",
    "Kalamata",
    "Tripoli",
    "Corinth",
    "Mytilene",
    "Kavala",
    "Veria",
    "Serres",
    "Drama",
    "Komotini",
    "Alexandroupoli",
    "Kozani",
    "Katerini",
    "Karditsa",
    "Trikala",
    "Lamia",
    "Pyrgos",
    "Rethymno",
    "Preveza",
    "Corfu",
    "Argos",
    "Piraeus",
    "Kerkyra",
    "Syros",
    "Zakynthos",
    "Nafplio",
    "Chios",
    "Samos"
  ],
  France: [
    "Paris",
    "Marseille",
    "Lyon",
    "Toulouse",
    "Nice",
    "Nantes",
    "Strasbourg",
    "Montpellier",
    "Bordeaux",
    "Lille",
    "Rennes",
    "Reims",
    "Le Havre",
    "Saint-Étienne",
    "Toulon",
    "Grenoble",
    "Dijon",
    "Angers",
    "Nîmes",
    "Villeurbanne",
    "Le Mans",
    "Aix-en-Provence",
    "Clermont-Ferrand",
    "Brest",
    "Limoges",
    "Tours",
    "Amiens",
    "Perpignan",
    "Metz",
    "Besançon",
    "Orléans",
    "Mulhouse",
    "Rouen",
    "Caen",
    "Nancy",
    "Saint-Denis",
    "Boulogne-Billancourt",
    "Argenteuil",
    "Montreuil",
    "Roubaix",
    "Nanterre",
    "Vitry-sur-Seine",
    "Avignon",
    "Créteil",
    "Versailles",
    "Poitiers"
  ],
  Finland: [
    "Helsinki",
    "Espoo",
    "Tampere",
    "Vantaa",
    "Oulu",
    "Turku",
    "Jyväskylä",
    "Lahti",
    "Kuopio",
    "Kouvola",
    "Pori",
    "Joensuu",
    "Lappeenranta",
    "Hämeenlinna",
    "Vaasa",
    "Seinäjoki",
    "Rovaniemi",
    "Mikkeli",
    "Salo",
    "Kokkola",
    "Porvoo",
    "Lohja",
    "Hyvinkää",
    "Nurmijärvi"
  ],
  Fiji: [
    "Suva",
    "Lautoka",
    "Nadi",
    "Labasa",
    "Ba",
    "Levuka",
    "Nausori",
    "Savusavu",
    "Tavua",
    "Sigatoka",
    "Rakiraki",
    "Lami",
    "Nasinu"
  ],
  Egypt: [
    "Cairo",
    "Alexandria",
    "Giza",
    "Shubra El-Kheima",
    "Port Said",
    "Suez",
    "Luxor",
    "El-Mansoura",
    "Tanta",
    "Asyut",
    "Ismailia",
    "Fayyum",
    "Zagazig",
    "Aswan",
    "Damietta",
    "Damanhur",
    "El-Mahalla El-Kubra",
    "Qena",
    "Sohag",
    "Hurghada",
    "Banha",
    "Kafr El-Sheikh",
    "Mansoura",
    "Beni Suef",
    "Shibin El Kom",
    "El Arish",
    "Qalyub",
    "Desouk",
    "Abu Kabir",
    "Mallawi",
    "Kafr El-Dawwar",
    "Elsahel",
    "Kom Ombo",
    "Dikirnis",
    "Armant",
    "Quesna",
    "Al-Balyana",
    "Matay",
    "Balasara",
    "Al-Hamra",
    "Tamy al-Amdid"
  ],
  "Eastern Caribbean": [
    "Bridgetown",
    "Castries",
    "Kingstown",
    "St. John's",
    "Roseau",
    "Basseterre",
    "St. George's",
    "Port of Spain",
    "Road Town",
    "Charlotte Amalie",
    "Philipsburg",
    "Saint-Pierre",
    "The Valley"
  ],
  "New Zealand": [
    "Auckland",
    "Wellington",
    "Christchurch",
    "Hamilton",
    "Tauranga",
    "Napier-Hastings",
    "Dunedin",
    "Palmerston North",
    "Nelson",
    "Rotorua",
    "Whangarei",
    "New Plymouth",
    "Invercargill",
    "Whanganui",
    "Gisborne",
    "Masterton",
    "Levin",
    "Tokoroa",
    "Ashburton",
    "Timaru",
    "Taupo",
    "Pukekohe East",
    "Whakatane",
    "Blenheim",
    "Gore",
    "Takanini",
    "Taumarunui",
    "Picton",
    "Kerikeri",
    "Waiuku",
    "Wanaka",
    "Waihi",
    "Katikati",
    "Queenstown",
    "Te Anau",
    "Waipawa",
    "Feilding",
    "Winton",
    "Te Kuiti",
    "Huntly",
    "Warkworth",
    "Turangi"
  ],
  Netherlands: [
    "Amsterdam",
    "Rotterdam",
    "The Hague",
    "Utrecht",
    "Eindhoven",
    "Tilburg",
    "Groningen",
    "Almere",
    "Breda",
    "Nijmegen",
    "Enschede",
    "Haarlem",
    "Arnhem",
    "Zaanstad",
    "Amersfoort",
    "Apeldoorn",
    "s-Hertogenbosch",
    "Hoofddorp",
    "Maastricht",
    "Leiden",
    "Dordrecht",
    "Zoetermeer",
    "Zwolle",
    "Deventer",
    "Delft",
    "Alkmaar",
    "Heerlen",
    "Venlo",
    "Leeuwarden",
    "Amstelveen",
    "Hilversum",
    "Hengelo",
    "Purmerend",
    "Roosendaal",
    "Oss",
    "Schiedam",
    "Spijkenisse",
    "Vlaardingen",
    "Almelo",
    "Gouda",
    "Zaandam",
    "Lelystad",
    "Alphen aan den Rijn",
    "Helmond",
    "Heerhugowaard",
    "Hilversum",
    "Zeist"
  ],
  Denmark: [
    "Copenhagen",
    "Aarhus",
    "Odense",
    "Aalborg",
    "Esbjerg",
    "Randers",
    "Kolding",
    "Horsens",
    "Vejle",
    "Roskilde",
    "Helsingør",
    "Herning",
    "Silkeborg",
    "Næstved",
    "Greve",
    "Tårnby",
    "Fredericia",
    "Ballerup",
    "Rødovre",
    "Viborg",
    "Køge",
    "Holstebro",
    "Taastrup",
    "Slagelse",
    "Hillerød",
    "Helsingborg",
    "Frederikshavn",
    "Hjørring",
    "Nørresundby",
    "Holbæk",
    "Sønderborg",
    "Frederikssund",
    "Ringsted",
    "Århus",
    "Frederiksværk",
    "Køge",
    "Nyborg",
    "Farum",
    "Ikast",
    "Vordingborg",
    "Nykøbing Falster"
  ],
  "Czech Republic": [
    "Prague",
    "Brno",
    "Ostrava",
    "Plzeň",
    "Liberec",
    "Olomouc",
    "České Budějovice",
    "Hradec Králové",
    "Ústí nad Labem",
    "Pardubice",
    "Zlín",
    "Havířov",
    "Kladno",
    "Most",
    "Opava",
    "Frýdek-Místek",
    "Karviná",
    "Jihlava",
    "Teplice",
    "Děčín",
    "Karlovy Vary",
    "Chomutov",
    "Jablonec nad Nisou",
    "Mladá Boleslav",
    "Prostějov",
    "Třebíč",
    "Třinec",
    "Česká Lípa",
    "Tábor",
    "Znojmo",
    "Přerov",
    "Cheb",
    "Kolin",
    "Trutnov",
    "Kroměříž",
    "Jindřichův Hradec",
    "Prostějov",
    "Písek",
    "Šumperk",
    "Jirkov",
    "Litvínov",
    "Havlíčkův Brod"
  ],
  Cyprus: [
    "Nicosia",
    "Limassol",
    "Larnaca",
    "Famagusta",
    "Paphos",
    "Kyrenia",
    "Protaras",
    "Ayia Napa",
    "Paralimni",
    "Polis",
    "Lefka",
    "Morphou",
    "Xylophagou",
    "Deryneia",
    "Sotira",
    "Mouttagiaka",
    "Dherynia",
    "Kato Pyrgos",
    "Pyla",
    "Peristerona",
    "Vrysoulles",
    "Avgorou",
    "Lysos",
    "Pachyammos",
    "Zygi",
    "Kornos",
    "Athienou",
    "Arsos",
    "Achna",
    "Argaka",
    "Lageia",
    "Neo Chorio",
    "Kissonerga",
    "Pissouri",
    "Agros",
    "Tala",
    "Platres",
    "Kato Akourdalia",
    "Episkopi",
    "Kakopetria"
  ],
  Chile: [
    "Santiago",
    "Valparaíso",
    "Concepción",
    "Viña del Mar",
    "Antofagasta",
    "Valdivia",
    "La Serena",
    "Arica",
    "Iquique",
    "Rancagua",
    "Talca",
    "Temuco",
    "Puerto Montt",
    "Chillán",
    "Curicó",
    "Osorno",
    "Calama",
    "Coquimbo",
    "Puente Alto",
    "San Bernardo",
    "La Florida",
    "Peñalolén",
    "Maipú",
    "Puente Alto",
    "Talcahuano",
    "Ñuñoa",
    "Quilpué",
    "Valdivia",
    "San Felipe",
    "Los Ángeles",
    "Punta Arenas",
    "Lo Barnechea",
    "Chicureo Abajo",
    "Vitacura",
    "Cerrillos",
    "Colina",
    "Melipilla",
    "Paine",
    "Puerto Varas",
    "Lampa",
    "Padre Hurtado",
    "San Vicente",
    "La Cisterna",
    "San Antonio",
    "Villa Alemana",
    "Concón"
  ],
  Austria: [
    "Vienna",
    "Graz",
    "Linz",
    "Salzburg",
    "Innsbruck",
    "Klagenfurt",
    "Villach",
    "Wels",
    "Sankt Pölten",
    "Dornbirn",
    "Wiener Neustadt",
    "Steyr",
    "Feldkirch",
    "Bregenz",
    "Leoben",
    "Klosterneuburg",
    "Baden",
    "Wolfsberg",
    "Leonding",
    "Krems",
    "Traun",
    "Amstetten",
    "Lustenau",
    "Kapfenberg",
    "Hallein",
    "Kufstein",
    "Traiskirchen",
    "Schwechat",
    "Braunau am Inn",
    "Stockerau",
    "Saalfelden",
    "Ansfelden",
    "Tulln",
    "Hohenems",
    "Spittal an der Drau",
    "Telfs",
    "Ternitz",
    "Perchtoldsdorf",
    "Feldkirchen",
    "Bludenz",
    "Bad Ischl",
    "Marchtrenk",
    "Waidhofen",
    "Gmunden"
  ],
  Malta: [
    "Valletta",
    "Birkirkara",
    "Mosta",
    "Qormi",
    "Sliema",
    "Zejtun",
    "Rabat",
    "Naxxar",
    "Żabbar",
    "San Ġwann",
    "Fgura",
    "Żejtun",
    "Żebbuġ",
    "Senglea",
    "Żejtun",
    "Marsa",
    "Santa Venera",
    "Luqa",
    "Gżira",
    "Żejtun",
    "San Pawl il-Baħar",
    "Birżebbuġa",
    "Marsaskala",
    "Attard",
    "Paola",
    "Marsaxlokk",
    "Balzan",
    "Dingli",
    "Mġarr",
    "Xgħajra",
    "Mtarfa",
    "Kalkara",
    "Żurrieq",
    "Qrendi",
    "Gudja",
    "Safi",
    "Siġġiewi",
    "Mqabba",
    "Ta' Xbiex",
    "Mellieħa",
    "Pembroke",
    "Msida"
  ],
  Lithuania: [
    "Vilnius",
    "Kaunas",
    "Klaipėda",
    "Šiauliai",
    "Panevėžys",
    "Alytus",
    "Marijampolė",
    "Mažeikiai",
    "Jonava",
    "Utena",
    "Kėdainiai",
    "Telšiai",
    "Visaginas",
    "Tauragė",
    "Šilutė",
    "Kretinga",
    "Širvintos",
    "Radviliškis",
    "Palanga",
    "Druskininkai",
    "Rokiškis",
    "Gargždai",
    "Biržai",
    "Kuršėnai",
    "Garliava",
    "Joniškis",
    "Vilkaviškis",
    "Raseiniai",
    "Anykščiai",
    "Naujoji Akmenė",
    "Elektrėnai",
    "Jurbarkas",
    "Prienai",
    "Kelme",
    "Kupiskis",
    "Šalčininkai",
    "Pasvalys",
    "Zarasai",
    "Plungė",
    "Silale",
    "Lazdijai"
  ],
  Slovenia: [
    "Ljubljana",
    "Maribor",
    "Celje",
    "Kranj",
    "Velenje",
    "Koper",
    "Novo Mesto",
    "Ptuj",
    "Trbovlje",
    "Kamnik",
    "Jesenice",
    "Nova Gorica",
    "Murska Sobota",
    "Škofja Loka",
    "Domžale",
    "Izola",
    "Postojna",
    "Logatec",
    "Slovenj Gradec",
    "Ravne na Koroškem",
    "Litija",
    "Brežice",
    "Radovljica",
    "Krško",
    "Ajdo",
    "Grosuplje",
    "Lucija",
    "Žalec",
    "Kocevje",
    "Tržič",
    "Zagorje ob Savi",
    "Slovenska Bistrica",
    "Mengeš",
    "Trebnje",
    "Vrhnika",
    "Lenart v Slovenskih Goricah",
    "Šentjur",
    "Ormož",
    "Cerknica",
    "Sevnica",
    "Šempeter pri Gorici",
    "Rogaška Slatina",
    "Šenčur",
    "Bled"
  ],

  
  
  
  
  
    
  
  
  
  




}