export const subscriberList = {
  id: "5f0dd2f08db53f0001acaa3a",
  uid: "10000000000",
  borrowerProfile: {
    msisdn: "966500751048",
    firstNameEn: "MAHESH",
    middleNameEn: "PARASRAM",
    lastNameEn: "LALWANI",
    firstNameAr: "علي",
    middleNameAr: "يوسف",
    lastNameAr: "علي",
    gender: "MALE",
    dateOfBirth: "1992-04-21",
    idType: "NATIONAL_ID",
    idNumber: "10000000000",
    idExpiryDate: "2027-02-03",
    occupation: "N/A",
    nationality: "المملكة",
    residenceDetails: {
      buildingNumber: "A202",
      streetName: "Balewadi",
      city: "Pune",
      postOfficeBox: "32511",
      neighborhood: "Baner",
      additionalNumbers: "4156",
      rent: false,
      unitNumber: "20",
    },
    totalMonthlyExpenses: 0.0,
    maritalDetails: {
      maritalStatus: "Single",
      noOfDomesticWorkers: 0,
      noOfChildren: 0,
      totalDependent: 1,
    },
    registrationDate: "2022-08-08T00:00:00.000Z",
    recentGosiData: null,
  },
  recentGosiData: {
    gosiResponseId: "c975aa6a-df5d-4137-9617-9ee5e1274395",
    employmentStatusInfo: [
      {
        fullName: "Mahesh Parasram Lalwani",
        basicWage: 3000.0,
        housingAllowance: 1000.0,
        otherAllowance: 1000.0,
        employerName: "Photon Matters",
        dateOfJoining: "01/04/20",
        workingMonths: "44",
        employmentStatus: "Employed",
        salaryStartingDate: "01/01/22",
        establishmentActivity: "Private Company",
      },
    ],
    idExistanceInGosi: "EXIST",
    fetchingDate: "2023-12-24T16:09:06.398Z",
    expiryDate: "2025-01-23T16:09:06.399Z",
  },
  borrowerEligibilityStatus: "ELIGIBLE",
  loans: {
    "c7872e19-1111-488f-85a8-4e2f85a65885": {
      loanId: "c7872e19-d2b3-488f-85a8-4e2f85a65885",
      loanType: "UNSECURED_RETAIL_LOAN",
      amount: 4967.999878559221,
      projectId: null,
      installments: null,
      loanStatus: "CLOSED",
      loanPaymentDetails: {
        status: true,
        transactionId: "778cfa5f-91ca-4b40-816f-300ffea93aa5",
        processDate: "2022-08-10 10:02:50",
        amount: 4968.0,
      },
      contractNumber: "10760442291660028650034",
    },
  },
  deactivated: false,
  reactivationDate: "2022-08-08T03:36:25.987Z",
};

export const creditProfileList = [
  {
    projectName: "Zain Tamam Cash",
    netTCL: 245179.15,
  },
  {
    projectName: "Zain Tamam Cash",
    netTCL: 250000.0,
  },
];

export const loanOfferCal = {
  id: "65c5379779c8b9000198d7ce",
  uid: "10000000000",
  gosiFullWage: 13197.0,
  gosiDeduction: 708.0,
  netIncome: 12489.0,
  simahLiabilitiesTotalMontllyInstallments: {
    consumer: 5794.65,
    gdbrWithoutMTG: 5794.65,
    gdbrWithMTG: 5794.65,
  },
  simahLiabilitiesDBR: {
    consumer: 0.464,
    gdbrWithoutMTG: 0.464,
    gdbrWithMTG: 0.464,
  },
  simahLiabilitiesRemainingDBR: {
    consumer: -0.014999999,
    gdbrWithoutMTG: -0.014999999,
    gdbrWithMTG: 0.08500002,
  },
  disposableIncome: -205.64999999999964,
  eligibleDBR: 0.0,
  eligibleEMI: 0.0,
  adjustedEMI: -206.65,
  propensityToPay: -0.01654656097365679,
  simahScore: 603.0,
  creditScore: 0.58,
  calculationDate: "2024-02-08T23:20:39.079Z",
  bareMinimumExpenses: 6900.0,
  totalMonthlyExpenses: 6300.0,
};

export const loans = [
  {
    loanId: "c7872e19-1111-488f-85a8-4e2f85a65885",
    loanType: "UNSECURED_RETAIL_LOAN",
    loanStatus: 3,
    loanAmount: 4967.999878559221,
    totalAmount: 8843.04,
    submitDate: "2022-08-01 00:00:00",
    paidDate: "2022-08-10 10:02:50",
    outstandingPrincipal: 0.0,
    missedInstallmentsNumber: 0,
    installments: [
      {
        installmentId: "c7872e19-1111-488f-85a8-4e2f85a65885-1",
        paid: true,
        amount: 491.28,
        installmentDate: "2022-09-01",
        totalRequiredAmount: 491.28,
        princpleValue: 147.15,
        interestValue: 344.13,
        installmentStatus: "Paid",
      },
      {
        installmentId: "c7872e19-1111-488f-85a8-4e2f85a65885-2",
        paid: true,
        amount: 491.28,
        installmentDate: "2022-10-01",
        totalRequiredAmount: 491.28,
        princpleValue: 157.34,
        interestValue: 333.94,
        installmentStatus: "Paid",
      },
      {
        installmentId: "c7872e19-1111-488f-85a8-4e2f85a65885-3",
        paid: true,
        amount: 491.28,
        installmentDate: "2022-11-01",
        totalRequiredAmount: 491.28,
        princpleValue: 168.24,
        interestValue: 323.04,
        installmentStatus: "Paid",
      },
      {
        installmentId: "c7872e19-1111-488f-85a8-4e2f85a65885-4",
        paid: true,
        amount: 491.28,
        installmentDate: "2022-12-01",
        totalRequiredAmount: 491.28,
        princpleValue: 179.9,
        interestValue: 311.38,
        installmentStatus: "Paid",
      },
      {
        installmentId: "c7872e19-1111-488f-85a8-4e2f85a65885-5",
        paid: true,
        amount: 491.28,
        installmentDate: "2023-01-01",
        totalRequiredAmount: 491.28,
        princpleValue: 192.36,
        interestValue: 298.92,
        installmentStatus: "Paid",
      },
      {
        installmentId: "c7872e19-1111-488f-85a8-4e2f85a65885-6",
        paid: true,
        amount: 491.28,
        installmentDate: "2023-05-01",
        totalRequiredAmount: 491.28,
        princpleValue: 205.68,
        interestValue: 285.6,
        installmentStatus: "Paid",
      },
      {
        installmentId: "c7872e19-1111-488f-85a8-4e2f85a65885-7",
        paid: true,
        amount: 491.28,
        installmentDate: "2023-06-01",
        totalRequiredAmount: 491.28,
        princpleValue: 219.93,
        interestValue: 271.35,
        installmentStatus: "Paid",
      },
      {
        installmentId: "c7872e19-1111-488f-85a8-4e2f85a65885-8",
        paid: true,
        amount: 491.28,
        installmentDate: "2023-07-01",
        totalRequiredAmount: 491.28,
        princpleValue: 235.16,
        interestValue: 256.12,
        installmentStatus: "Paid",
      },
      {
        installmentId: "c7872e19-1111-488f-85a8-4e2f85a65885-9",
        paid: true,
        amount: 491.28,
        installmentDate: "2023-08-01",
        totalRequiredAmount: 491.28,
        princpleValue: 251.45,
        interestValue: 239.83,
        installmentStatus: "Paid",
      },
      {
        installmentId: "c7872e19-1111-488f-85a8-4e2f85a65885-10",
        paid: true,
        amount: 491.28,
        installmentDate: "2023-09-01",
        totalRequiredAmount: 491.28,
        princpleValue: 268.87,
        interestValue: 222.41,
        installmentStatus: "Paid",
      },
      {
        installmentId: "c7872e19-1111-488f-85a8-4e2f85a65885-11",
        paid: true,
        amount: 491.28,
        installmentDate: "2023-10-01",
        totalRequiredAmount: 491.28,
        princpleValue: 287.5,
        interestValue: 203.78,
        installmentStatus: "Paid",
      },
      {
        installmentId: "c7872e19-1111-488f-85a8-4e2f85a65885-12",
        paid: true,
        amount: 491.28,
        installmentDate: "2023-11-01",
        totalRequiredAmount: 491.28,
        princpleValue: 307.41,
        interestValue: 183.87,
        installmentStatus: "Paid",
      },
      {
        installmentId: "c7872e19-1111-488f-85a8-4e2f85a65885-13",
        paid: true,
        amount: 491.28,
        installmentDate: "2023-12-01",
        totalRequiredAmount: 491.28,
        princpleValue: 328.7,
        interestValue: 162.58,
        installmentStatus: "Paid",
      },
      {
        installmentId: "c7872e19-1111-488f-85a8-4e2f85a65885-14",
        paid: true,
        amount: 491.28,
        installmentDate: "2024-01-01",
        totalRequiredAmount: 491.28,
        princpleValue: 351.47,
        interestValue: 139.81,
        installmentStatus: "Paid",
      },
      {
        installmentId: "c7872e19-1111-488f-85a8-4e2f85a65885-15",
        paid: true,
        amount: 491.28,
        installmentDate: "2024-02-01",
        totalRequiredAmount: 491.28,
        princpleValue: 375.82,
        interestValue: 115.46,
        installmentStatus: "Paid",
      },
      {
        installmentId: "c7872e19-1111-488f-85a8-4e2f85a65885-16",
        paid: true,
        amount: 491.28,
        installmentDate: "2024-03-01",
        totalRequiredAmount: 491.28,
        princpleValue: 401.85,
        interestValue: 89.43,
        installmentStatus: "Paid",
      },
      {
        installmentId: "c7872e19-1111-488f-85a8-4e2f85a65885-17",
        paid: true,
        amount: 491.28,
        installmentDate: "2024-04-01",
        totalRequiredAmount: 491.28,
        princpleValue: 429.69,
        interestValue: 61.59,
        installmentStatus: "Paid",
      },
      {
        installmentId: "c7872e19-1111-488f-85a8-4e2f85a65885-18",
        paid: true,
        amount: 491.28,
        installmentDate: "2024-05-01",
        totalRequiredAmount: 491.28,
        princpleValue: 459.48,
        interestValue: 31.8,
        installmentStatus: "Paid",
      },
    ],
  },
  {
    loanId: "c7872e19-1111-488f-85a8-4e2f85a65884",
    loanType: "UNSECURED_RETAIL_LOAN",
    loanStatus: 3,
    loanAmount: 4967.999878559221,
    totalAmount: 8843.04,
    submitDate: "2022-08-02 00:00:00",
    paidDate: "2022-08-11 10:02:50",
    outstandingPrincipal: 0.0,
    missedInstallmentsNumber: 0,
    installments: [
      {
        installmentId: "c7872e19-1111-488f-85a8-4e2f85a65885-1",
        paid: true,
        amount: 491.28,
        installmentDate: "2022-09-01",
        totalRequiredAmount: 491.28,
        princpleValue: 147.15,
        interestValue: 344.13,
        installmentStatus: "Paid",
      },
      {
        installmentId: "c7872e19-1111-488f-85a8-4e2f85a65885-2",
        paid: true,
        amount: 491.28,
        installmentDate: "2022-10-01",
        totalRequiredAmount: 491.28,
        princpleValue: 157.34,
        interestValue: 333.94,
        installmentStatus: "Paid",
      },
      {
        installmentId: "c7872e19-1111-488f-85a8-4e2f85a65885-3",
        paid: true,
        amount: 491.28,
        installmentDate: "2022-11-01",
        totalRequiredAmount: 491.28,
        princpleValue: 168.24,
        interestValue: 323.04,
        installmentStatus: "Paid",
      },
      {
        installmentId: "c7872e19-1111-488f-85a8-4e2f85a65885-4",
        paid: true,
        amount: 491.28,
        installmentDate: "2022-12-01",
        totalRequiredAmount: 491.28,
        princpleValue: 179.9,
        interestValue: 311.38,
        installmentStatus: "Paid",
      },
      {
        installmentId: "c7872e19-1111-488f-85a8-4e2f85a65885-5",
        paid: true,
        amount: 491.28,
        installmentDate: "2023-01-01",
        totalRequiredAmount: 491.28,
        princpleValue: 192.36,
        interestValue: 298.92,
        installmentStatus: "Paid",
      },
      {
        installmentId: "c7872e19-1111-488f-85a8-4e2f85a65885-6",
        paid: true,
        amount: 491.28,
        installmentDate: "2023-05-01",
        totalRequiredAmount: 491.28,
        princpleValue: 205.68,
        interestValue: 285.6,
        installmentStatus: "Paid",
      },
      {
        installmentId: "c7872e19-1111-488f-85a8-4e2f85a65885-7",
        paid: true,
        amount: 491.28,
        installmentDate: "2023-06-01",
        totalRequiredAmount: 491.28,
        princpleValue: 219.93,
        interestValue: 271.35,
        installmentStatus: "Paid",
      },
      {
        installmentId: "c7872e19-1111-488f-85a8-4e2f85a65885-8",
        paid: true,
        amount: 491.28,
        installmentDate: "2023-07-01",
        totalRequiredAmount: 491.28,
        princpleValue: 235.16,
        interestValue: 256.12,
        installmentStatus: "Paid",
      },
      {
        installmentId: "c7872e19-1111-488f-85a8-4e2f85a65885-9",
        paid: true,
        amount: 491.28,
        installmentDate: "2023-08-01",
        totalRequiredAmount: 491.28,
        princpleValue: 251.45,
        interestValue: 239.83,
        installmentStatus: "Paid",
      },
      {
        installmentId: "c7872e19-1111-488f-85a8-4e2f85a65885-10",
        paid: true,
        amount: 491.28,
        installmentDate: "2023-09-01",
        totalRequiredAmount: 491.28,
        princpleValue: 268.87,
        interestValue: 222.41,
        installmentStatus: "Paid",
      },
      {
        installmentId: "c7872e19-1111-488f-85a8-4e2f85a65885-11",
        paid: true,
        amount: 491.28,
        installmentDate: "2023-10-01",
        totalRequiredAmount: 491.28,
        princpleValue: 287.5,
        interestValue: 203.78,
        installmentStatus: "Paid",
      },
      {
        installmentId: "c7872e19-1111-488f-85a8-4e2f85a65885-12",
        paid: true,
        amount: 491.28,
        installmentDate: "2023-11-01",
        totalRequiredAmount: 491.28,
        princpleValue: 307.41,
        interestValue: 183.87,
        installmentStatus: "Paid",
      },
      {
        installmentId: "c7872e19-1111-488f-85a8-4e2f85a65885-13",
        paid: true,
        amount: 491.28,
        installmentDate: "2023-12-01",
        totalRequiredAmount: 491.28,
        princpleValue: 328.7,
        interestValue: 162.58,
        installmentStatus: "Paid",
      },
      {
        installmentId: "c7872e19-1111-488f-85a8-4e2f85a65885-14",
        paid: true,
        amount: 491.28,
        installmentDate: "2024-01-01",
        totalRequiredAmount: 491.28,
        princpleValue: 351.47,
        interestValue: 139.81,
        installmentStatus: "Paid",
      },
      {
        installmentId: "c7872e19-1111-488f-85a8-4e2f85a65885-15",
        paid: true,
        amount: 491.28,
        installmentDate: "2024-02-01",
        totalRequiredAmount: 491.28,
        princpleValue: 375.82,
        interestValue: 115.46,
        installmentStatus: "Paid",
      },
      {
        installmentId: "c7872e19-1111-488f-85a8-4e2f85a65885-16",
        paid: true,
        amount: 491.28,
        installmentDate: "2024-03-01",
        totalRequiredAmount: 491.28,
        princpleValue: 401.85,
        interestValue: 89.43,
        installmentStatus: "Paid",
      },
      {
        installmentId: "c7872e19-1111-488f-85a8-4e2f85a65885-17",
        paid: true,
        amount: 491.28,
        installmentDate: "2024-04-01",
        totalRequiredAmount: 491.28,
        princpleValue: 429.69,
        interestValue: 61.59,
        installmentStatus: "Paid",
      },
      {
        installmentId: "c7872e19-1111-488f-85a8-4e2f85a65885-18",
        paid: true,
        amount: 491.28,
        installmentDate: "2024-05-01",
        totalRequiredAmount: 491.28,
        princpleValue: 459.48,
        interestValue: 31.8,
        installmentStatus: "Paid",
      },
    ],
  },
];

export const repayments = [
  {
    uid: "10000000000",
    repaymentStatus: 4,
    loanId: "c7872e19-d2b3-488f-85a8-4e2f85a65885",
    processDate: "2022-08-10 07:02:50",
    repaymentAmount: 57.13,
    repaymentOriginator: "USER_PAYMENT",
  },
  {
    uid: "10000000000",
    repaymentStatus: 4,
    loanId: "c7872e19-d2b3-488f-85a8-4e2f85a65885",
    processDate: "2022-09-10 08:39:13",
    repaymentAmount: 491.28,
    repaymentOriginator: "USER_PAYMENT",
  },
  {
    uid: "10000000000",
    repaymentStatus: 2,
    loanId: "c7872e19-d2b3-488f-85a8-4e2f85a65885",
    processDate: "2022-10-10 08:39:13",
    repaymentAmount: 491.28,
    repaymentOriginator: "AUTO_PAYMENT",
  },
  {
    uid: "10000000000",
    repaymentStatus: 2,
    loanId: "c7872e19-d2b3-488f-85a8-4e2f85a65885",
    processDate: "2022-11-10 08:39:13",
    repaymentAmount: 491.28,
    repaymentOriginator: "AUTO_PAYMENT",
  },
  {
    uid: "10000000000",
    repaymentStatus: 2,
    loanId: "c7872e19-d2b3-488f-85a8-4e2f85a65885",
    processDate: "2022-12-10 08:39:13",
    repaymentAmount: 491.28,
    repaymentOriginator: "AUTO_PAYMENT",
  },
  {
    uid: "10000000000",
    repaymentStatus: 2,
    loanId: "c7872e19-d2b3-488f-85a8-4e2f85a65885",
    processDate: "2023-01-10 08:39:13",
    repaymentAmount: 491.28,
    repaymentOriginator: "AUTO_PAYMENT",
  },
  {
    uid: "10000000000",
    repaymentStatus: 2,
    loanId: "c7872e19-d2b3-488f-85a8-4e2f85a65885",
    processDate: "2023-02-10 08:39:13",
    repaymentAmount: 491.28,
    repaymentOriginator: "AUTO_PAYMENT",
  },
  {
    uid: "10000000000",
    repaymentStatus: 2,
    loanId: "c7872e19-d2b3-488f-85a8-4e2f85a65885",
    processDate: "2023-03-10 08:39:13",
    repaymentAmount: 491.28,
    repaymentOriginator: "AUTO_PAYMENT",
  },
];

export const rejectionHistory = [
  {
    id: "5f21313769d0750001360792",
    uid: "10000000000",
    rejectionReason: "Invalid grossSalary criteria",
    rejectionDate: "2020-07-29T11:20:07.530Z",
  },
  {
    id: "65cffadd534737000125dc3a",
    uid: "10000000000",
    rejectionReason:
      "you exceeded your count of active loans from this product ",
    rejectionDate: "2024-02-17T03:16:29.650Z",
  },
  {
    id: "65d8e4c6aad6300001eaa64d",
    uid: "10000000000",
    rejectionReason: "User Not Active in GOSI",
    rejectionDate: "2024-02-23T21:32:38.421Z",
  },
];

export const CBDetails = {
  userId: "10000000000",
  reportId: "20db0a7a-e5dc-47ef-bf39-6e7f0d72bdae",
  creationDate: [2023, 12, 24],
  expiryDate: [2025, 1, 14],
  response: {
    service: "ENQUIRY",
    versionno: "2.0",
    action: "A_SC",
    status: "OK",
    header: {
      memberid: "496",
      userid: "B2BZANP",
      runno: "1769346",
      totitems: "1",
      erritems: "",
    },
    message: {
      item: [
        {
          enquiryreference: "20DB0A7A-E5DC-47EF-BF39-6E7F0D72BDAE",
          rspreport: {
            enquirytype: "NA",
            reportdate: "24/12/2023",
            enquiryno: "4256725120",
            producttype: "PLN",
            noofapplicants: "1",
            accounttype: "S",
            enquiryreference: "20DB0A7A-E5DC-47EF-BF39-6E7F0D72BDAE",
            amount: "8000.00",
            mbrtype: "FULL",
            mbrsts: "ACTIV",
            prcdpt: null,
            enqrsn: null,
            ficog4: "Y",
            consumer: [
              {
                entity: "21376362",
                capl: "P",
                cid: {
                  cid1: "T",
                  cid2: "1076044229",
                  cid3: "03/02/2027",
                },
                cvip: "",
                provided: {
                  pcnam: {
                    pcnmfa: {
                      value: "??????",
                      lang: "ar",
                    },
                    pcnm1A: {
                      value: "????",
                      lang: "ar",
                    },
                    pcnm2A: {
                      value: "????",
                      lang: "ar",
                    },
                    pcnm3A: {
                      value: "??????",
                      lang: "ar",
                    },
                    pcnmfe: "ALMUSHARRAF",
                    pcnm1E: "RASHED",
                    pcnm2E: "YOUSEF",
                    pcnm3E: "ALMUSHARRAF",
                  },
                  pcdob: "21/04/1992",
                  pcgnd: "M",
                  pcmar: "S",
                  pcnat: "SAU",
                  pceml: "",
                },
                available: {
                  acnam: {
                    acnmfa: {
                      value: "المشرف",
                      lang: "ar",
                    },
                    acnm1A: {
                      value: "راشد",
                      lang: "ar",
                    },
                    acnm2A: null,
                    acnm3A: null,
                    acnm7A: null,
                    acnmfe: "ALMUSHARRAF",
                    acnm1E: "RASHED",
                    acnm2E: null,
                    acnm3E: null,
                    acnm7E: null,
                  },
                  acdob: "21/04/1992",
                  acgnd: "M",
                  acmar: "S",
                  acnat: "SAU",
                  aceml: "RA.Yo_2015@hotmail.com",
                },
                prevenquiries: {
                  prevenquiry: [
                    {
                      pedate: "07/09/2023",
                      peinqr: "MALM",
                      petype: "RV",
                      pemembref: "20230907BULKENQ202309071219582712",
                      peprd: "PLN",
                      peamount: "0.00",
                      pename: {
                        penmfa: null,
                        penm1A: null,
                        penm2A: null,
                        penm3A: null,
                        penmfe: null,
                        penm1E: null,
                        penm2E: null,
                        penm3E: null,
                      },
                      persn: null,
                    },
                    {
                      pedate: "30/10/2022",
                      peinqr: "ECFF",
                      petype: "NA",
                      pemembref: "EFKSA_15271413",
                      peprd: "PLN",
                      peamount: "56551.91",
                      pename: {
                        penmfa: null,
                        penm1A: null,
                        penm2A: null,
                        penm3A: null,
                        penmfe: null,
                        penm1E: null,
                        penm2E: null,
                        penm3E: null,
                      },
                      persn: null,
                    },
                    {
                      pedate: "05/10/2022",
                      peinqr: "TYAC",
                      petype: "NA",
                      pemembref: "32105102200062797",
                      peprd: "VLS",
                      peamount: "11000.00",
                      pename: {
                        penmfa: null,
                        penm1A: null,
                        penm2A: null,
                        penm3A: null,
                        penmfe: null,
                        penm1E: null,
                        penm2E: null,
                        penm3E: null,
                      },
                      persn: null,
                    },
                    {
                      pedate: "30/08/2022",
                      peinqr: "UCFS",
                      petype: "NA",
                      pemembref: "S3VVDNOBQE",
                      peprd: "CDC",
                      peamount: "0.00",
                      pename: {
                        penmfa: null,
                        penm1A: null,
                        penm2A: null,
                        penm3A: null,
                        penmfe: null,
                        penm1E: null,
                        penm2E: null,
                        penm3E: null,
                      },
                      persn: null,
                    },
                    {
                      pedate: "08/08/2022",
                      peinqr: "ZANP",
                      petype: "NA",
                      pemembref: "81AFDA47-66E5-4353-BF81-2BE611D5E69F",
                      peprd: "PLN",
                      peamount: "8000.00",
                      pename: {
                        penmfa: null,
                        penm1A: null,
                        penm2A: null,
                        penm3A: null,
                        penmfe: null,
                        penm1E: null,
                        penm2E: null,
                        penm3E: null,
                      },
                      persn: null,
                    },
                    {
                      pedate: "29/07/2022",
                      peinqr: "MALM",
                      petype: "NA",
                      pemembref: "F92761A6-09B0-4643-B3B6-DF429951A80B",
                      peprd: "PLN",
                      peamount: "10000.00",
                      pename: {
                        penmfa: null,
                        penm1A: null,
                        penm2A: null,
                        penm3A: null,
                        penmfe: null,
                        penm1E: null,
                        penm2E: null,
                        penm3E: null,
                      },
                      persn: null,
                    },
                    {
                      pedate: "19/07/2022",
                      peinqr: "ECFF",
                      petype: "NA",
                      pemembref: "EFKSA_13020527",
                      peprd: "PLN",
                      peamount: "56551.91",
                      pename: {
                        penmfa: null,
                        penm1A: null,
                        penm2A: null,
                        penm3A: null,
                        penmfe: null,
                        penm1E: null,
                        penm2E: null,
                        penm3E: null,
                      },
                      persn: null,
                    },
                    {
                      pedate: "14/04/2022",
                      peinqr: "ECFF",
                      petype: "NA",
                      pemembref: "EFKSA_10844402",
                      peprd: "PLN",
                      peamount: "63807.07",
                      pename: {
                        penmfa: null,
                        penm1A: null,
                        penm2A: null,
                        penm3A: null,
                        penmfe: null,
                        penm1E: null,
                        penm2E: null,
                        penm3E: null,
                      },
                      persn: null,
                    },
                    {
                      pedate: "27/03/2022",
                      peinqr: "TMRA",
                      petype: "SC",
                      pemembref: "A28C510A-7C31-43E9-B0BB-B5C7E1665009",
                      peprd: "CDL",
                      peamount: "1220.00",
                      pename: {
                        penmfa: null,
                        penm1A: null,
                        penm2A: null,
                        penm3A: null,
                        penmfe: null,
                        penm1E: null,
                        penm2E: null,
                        penm3E: null,
                      },
                      persn: null,
                    },
                    {
                      pedate: "14/03/2022",
                      peinqr: "ECFF",
                      petype: "NA",
                      pemembref: "EFKSA_10138994",
                      peprd: "PLN",
                      peamount: "66171.17",
                      pename: {
                        penmfa: null,
                        penm1A: null,
                        penm2A: null,
                        penm3A: null,
                        penmfe: null,
                        penm1E: null,
                        penm2E: null,
                        penm3E: null,
                      },
                      persn: null,
                    },
                    {
                      pedate: "07/07/2021",
                      peinqr: "ECFF",
                      petype: "NA",
                      pemembref: "EFKSA_1907235",
                      peprd: "PLN",
                      peamount: "76183.14",
                      pename: {
                        penmfa: null,
                        penm1A: null,
                        penm2A: null,
                        penm3A: null,
                        penmfe: null,
                        penm1E: null,
                        penm2E: null,
                        penm3E: null,
                      },
                      persn: null,
                    },
                    {
                      pedate: "02/07/2021",
                      peinqr: "ECFF",
                      petype: "NA",
                      pemembref: "EFKSA_1577530",
                      peprd: "PLN",
                      peamount: "76183.14",
                      pename: {
                        penmfa: null,
                        penm1A: null,
                        penm2A: null,
                        penm3A: null,
                        penmfe: null,
                        penm1E: null,
                        penm2E: null,
                        penm3E: null,
                      },
                      persn: null,
                    },
                    {
                      pedate: "19/06/2021",
                      peinqr: "ECFF",
                      petype: "NA",
                      pemembref: "EFKSA_1244155",
                      peprd: "PLN",
                      peamount: "70088.49",
                      pename: {
                        penmfa: null,
                        penm1A: null,
                        penm2A: null,
                        penm3A: null,
                        penmfe: null,
                        penm1E: null,
                        penm2E: null,
                        penm3E: null,
                      },
                      persn: null,
                    },
                    {
                      pedate: "06/06/2021",
                      peinqr: "UTIL",
                      petype: "RV",
                      pemembref: "A01272E2C67C11EBBCCF8F694D94CA7B",
                      peprd: "MBL",
                      peamount: "0.00",
                      pename: {
                        penmfa: null,
                        penm1A: null,
                        penm2A: null,
                        penm3A: null,
                        penmfe: null,
                        penm1E: null,
                        penm2E: null,
                        penm3E: null,
                      },
                      persn: null,
                    },
                    {
                      pedate: "06/06/2021",
                      peinqr: "UTIL",
                      petype: "RV",
                      pemembref: "9B5D770FC67C11EB90C99DDED33436E3",
                      peprd: "MBL",
                      peamount: "0.00",
                      pename: {
                        penmfa: null,
                        penm1A: null,
                        penm2A: null,
                        penm3A: null,
                        penmfe: null,
                        penm1E: null,
                        penm2E: null,
                        penm3E: null,
                      },
                      persn: null,
                    },
                    {
                      pedate: "04/04/2021",
                      peinqr: "ECFF",
                      petype: "NA",
                      pemembref: "0000447724",
                      peprd: "PLN",
                      peamount: "25000.00",
                      pename: {
                        penmfa: null,
                        penm1A: null,
                        penm2A: null,
                        penm3A: null,
                        penmfe: null,
                        penm1E: null,
                        penm2E: null,
                        penm3E: null,
                      },
                      persn: null,
                    },
                    {
                      pedate: "27/03/2021",
                      peinqr: "UCFS",
                      petype: "NA",
                      pemembref: "RKU2MOT8MH",
                      peprd: "CDC",
                      peamount: "50000.00",
                      pename: {
                        penmfa: null,
                        penm1A: null,
                        penm2A: null,
                        penm3A: null,
                        penmfe: null,
                        penm1E: null,
                        penm2E: null,
                        penm3E: null,
                      },
                      persn: null,
                    },
                    {
                      pedate: "14/03/2021",
                      peinqr: "ZANP",
                      petype: "RV",
                      pemembref: "17C015D8-A6AB-4F44-AAF0-8E47B6C68202",
                      peprd: "PLN",
                      peamount: "8000.00",
                      pename: {
                        penmfa: null,
                        penm1A: null,
                        penm2A: null,
                        penm3A: null,
                        penmfe: null,
                        penm1E: null,
                        penm2E: null,
                        penm3E: null,
                      },
                      persn: null,
                    },
                    {
                      pedate: "24/02/2021",
                      peinqr: "UCFS",
                      petype: "NA",
                      pemembref: "FOWY9VURQJ",
                      peprd: "CDC",
                      peamount: "15000.00",
                      pename: {
                        penmfa: null,
                        penm1A: null,
                        penm2A: null,
                        penm3A: null,
                        penmfe: null,
                        penm1E: null,
                        penm2E: null,
                        penm3E: null,
                      },
                      persn: null,
                    },
                    {
                      pedate: "11/02/2021",
                      peinqr: "ZANP",
                      petype: "RV",
                      pemembref: "E9E743AC-769C-44A3-890B-5A2FC9559CE5",
                      peprd: "PLN",
                      peamount: "8000.00",
                      pename: {
                        penmfa: null,
                        penm1A: null,
                        penm2A: null,
                        penm3A: null,
                        penmfe: null,
                        penm1E: null,
                        penm2E: null,
                        penm3E: null,
                      },
                      persn: null,
                    },
                    {
                      pedate: "22/01/2021",
                      peinqr: "UCFS",
                      petype: "NA",
                      pemembref: "ZZ4YCQMDBU",
                      peprd: "CDC",
                      peamount: "25000.00",
                      pename: {
                        penmfa: null,
                        penm1A: null,
                        penm2A: null,
                        penm3A: null,
                        penmfe: null,
                        penm1E: null,
                        penm2E: null,
                        penm3E: null,
                      },
                      persn: null,
                    },
                    {
                      pedate: "22/08/2020",
                      peinqr: "ZANP",
                      petype: "RV",
                      pemembref: "FB7F226F-1418-48D7-8293-9C213C9E8911",
                      peprd: "PLN",
                      peamount: "8000.00",
                      pename: {
                        penmfa: null,
                        penm1A: null,
                        penm2A: null,
                        penm3A: null,
                        penmfe: null,
                        penm1E: null,
                        penm2E: null,
                        penm3E: null,
                      },
                      persn: null,
                    },
                    {
                      pedate: "15/07/2020",
                      peinqr: "ZANP",
                      petype: "NA",
                      pemembref: "CA0D61D9-E891-48A1-9774-303DB5438143",
                      peprd: "PLN",
                      peamount: "8000.00",
                      pename: {
                        penmfa: null,
                        penm1A: null,
                        penm2A: null,
                        penm3A: null,
                        penmfe: null,
                        penm1E: null,
                        penm2E: null,
                        penm3E: null,
                      },
                      persn: null,
                    },
                    {
                      pedate: "15/03/2020",
                      peinqr: "UCFS",
                      petype: "NA",
                      pemembref: "AVNMLU3CK9",
                      peprd: "CDC",
                      peamount: "30000.00",
                      pename: {
                        penmfa: null,
                        penm1A: null,
                        penm2A: null,
                        penm3A: null,
                        penmfe: null,
                        penm1E: null,
                        penm2E: null,
                        penm3E: null,
                      },
                      persn: null,
                    },
                    {
                      pedate: "10/02/2020",
                      peinqr: "UCFS",
                      petype: "NA",
                      pemembref: "J2FVK881RY",
                      peprd: "CDC",
                      peamount: "100000.00",
                      pename: {
                        penmfa: null,
                        penm1A: null,
                        penm2A: null,
                        penm3A: null,
                        penmfe: null,
                        penm1E: null,
                        penm2E: null,
                        penm3E: null,
                      },
                      persn: null,
                    },
                  ],
                },
                cidetails: {
                  cidetail: [
                    {
                      cicrdtr: "TMWL",
                      ciprd: "VIN",
                      ciaccno: "D3364728",
                      cilimit: "83280.00",
                      ciissudt: "27/05/2013",
                      ciprodexpdt: "01/07/2017",
                      cistatus: "W",
                      ciclsddt: "01/06/2014",
                      citnr: "48",
                      cifrq: "M",
                      ciinstl: "1735.00",
                      cisal: "N",
                      cisec: "NO",
                      cicub: "74605.00",
                      ciodb: "12145.00",
                      cilastamtpd: "1735.00",
                      cilastpaydt: "17/04/2014",
                      ciasofdt: "01/06/2014",
                      cinxtdudt: "",
                      cisummry: "W65556543221N",
                    },
                    {
                      cicrdtr: "BANK",
                      ciprd: "CRC",
                      ciaccno: "5691047437",
                      cilimit: "4000.00",
                      ciissudt: "09/10/2012",
                      ciprodexpdt: "",
                      cistatus: "W",
                      ciclsddt: "14/03/2015",
                      citnr: "0",
                      cifrq: "M",
                      ciinstl: "4525.40",
                      cisal: "N",
                      cisec: "NO",
                      cicub: "4525.40",
                      ciodb: "4525.40",
                      cilastamtpd: "4390.48",
                      cilastpaydt: "17/06/2014",
                      ciasofdt: "14/03/2015",
                      cinxtdudt: "",
                      cisummry: "W65432100210210000001003",
                    },
                    {
                      cicrdtr: "UTIL",
                      ciprd: "MBL",
                      ciaccno: "5140243436",
                      cilimit: "1100.00",
                      ciissudt: "20/09/2019",
                      ciprodexpdt: "",
                      cistatus: "W",
                      ciclsddt: "04/01/2022",
                      citnr: "0",
                      cifrq: "M",
                      ciinstl: "0.00",
                      cisal: "N",
                      cisec: "NO",
                      cicub: "7250.08",
                      ciodb: "7250.08",
                      cilastamtpd: "43.00",
                      cilastpaydt: "12/08/2021",
                      ciasofdt: "04/01/2022",
                      cinxtdudt: "",
                      cisummry: "W6543210FF0FFFFFF00F0FFF",
                    },
                    {
                      cicrdtr: "UTIL",
                      ciprd: "MBL",
                      ciaccno: "1000129850168744",
                      cilimit: "650.00",
                      ciissudt: "11/03/2010",
                      ciprodexpdt: "",
                      cistatus: "W",
                      ciclsddt: "07/11/2014",
                      citnr: "0",
                      cifrq: "M",
                      ciinstl: "0.00",
                      cisal: "N",
                      cisec: "CA",
                      cicub: "1104.08",
                      ciodb: "1104.08",
                      cilastamtpd: "565.00",
                      cilastpaydt: "28/12/2018",
                      ciasofdt: "07/11/2014",
                      cinxtdudt: "",
                      cisummry: "W65432100000000000000000",
                    },
                    {
                      cicrdtr: "UTIL",
                      ciprd: "LND",
                      ciaccno: "1000139817765864",
                      cilimit: "500.00",
                      ciissudt: "04/11/2014",
                      ciprodexpdt: "",
                      cistatus: "W",
                      ciclsddt: "26/08/2015",
                      citnr: "0",
                      cifrq: "M",
                      ciinstl: "0.00",
                      cisal: "N",
                      cisec: "CA",
                      cicub: "1108.57",
                      ciodb: "1108.57",
                      cilastamtpd: "0.00",
                      cilastpaydt: "",
                      ciasofdt: "26/08/2015",
                      cinxtdudt: "",
                      cisummry: "W65432100000000000000000",
                    },
                    {
                      cicrdtr: "UTIL",
                      ciprd: "LND",
                      ciaccno: "1000133012272006",
                      cilimit: "600.00",
                      ciissudt: "22/03/2014",
                      ciprodexpdt: "",
                      cistatus: "W",
                      ciclsddt: "24/01/2015",
                      citnr: "0",
                      cifrq: "M",
                      ciinstl: "0.00",
                      cisal: "N",
                      cisec: "CA",
                      cicub: "1193.51",
                      ciodb: "1193.51",
                      cilastamtpd: "0.00",
                      cilastpaydt: "",
                      ciasofdt: "24/01/2015",
                      cinxtdudt: "",
                      cisummry: "W65432100000000000000000",
                    },
                    {
                      cicrdtr: "UTIL",
                      ciprd: "LND",
                      ciaccno: "1000145564273476",
                      cilimit: "600.00",
                      ciissudt: "25/01/2015",
                      ciprodexpdt: "",
                      cistatus: "W",
                      ciclsddt: "27/10/2015",
                      citnr: "0",
                      cifrq: "M",
                      ciinstl: "0.00",
                      cisal: "N",
                      cisec: "CA",
                      cicub: "889.11",
                      ciodb: "889.11",
                      cilastamtpd: "0.00",
                      cilastpaydt: "",
                      ciasofdt: "27/10/2015",
                      cinxtdudt: "",
                      cisummry: "W65432100000000000000000",
                    },
                    {
                      cicrdtr: "UTIL",
                      ciprd: "LND",
                      ciaccno: "1000131021977850",
                      cilimit: "500.00",
                      ciissudt: "16/01/2014",
                      ciprodexpdt: "",
                      cistatus: "W",
                      ciclsddt: "26/11/2014",
                      citnr: "0",
                      cifrq: "M",
                      ciinstl: "0.00",
                      cisal: "N",
                      cisec: "CA",
                      cicub: "806.67",
                      ciodb: "806.67",
                      cilastamtpd: "0.00",
                      cilastpaydt: "",
                      ciasofdt: "26/11/2014",
                      cinxtdudt: "",
                      cisummry: "W65432100000000000000000",
                    },
                    {
                      cicrdtr: "UTIL",
                      ciprd: "MBL",
                      ciaccno: "1000111182878183",
                      cilimit: "200.00",
                      ciissudt: "11/03/2010",
                      ciprodexpdt: "",
                      cistatus: "S",
                      ciclsddt: "",
                      citnr: "0",
                      cifrq: "M",
                      ciinstl: "0.00",
                      cisal: "N",
                      cisec: "CA",
                      cicub: "240.98",
                      ciodb: "240.98",
                      cilastamtpd: "0.00",
                      cilastpaydt: "",
                      ciasofdt: "01/12/2023",
                      cinxtdudt: "",
                      cisummry: "RRRRRRRRRRRRRRRRRRRRRRRR",
                    },
                    {
                      cicrdtr: "UTIL",
                      ciprd: "MBL",
                      ciaccno: "5168467143",
                      cilimit: "350.00",
                      ciissudt: "17/11/2020",
                      ciprodexpdt: "",
                      cistatus: "C",
                      ciclsddt: "25/05/2021",
                      citnr: "0",
                      cifrq: "M",
                      ciinstl: "0.00",
                      cisal: "N",
                      cisec: "NO",
                      cicub: "0.00",
                      ciodb: "0.00",
                      cilastamtpd: "0.00",
                      cilastpaydt: "25/05/2021",
                      ciasofdt: "25/05/2021",
                      cinxtdudt: "",
                      cisummry: "CF10FFFM",
                    },
                    {
                      cicrdtr: "UTIL",
                      ciprd: "LND",
                      ciaccno: "5172345230",
                      cilimit: "600.00",
                      ciissudt: "19/01/2021",
                      ciprodexpdt: "",
                      cistatus: "C",
                      ciclsddt: "22/11/2022",
                      citnr: "0",
                      cifrq: "M",
                      ciinstl: "0.00",
                      cisal: "N",
                      cisec: "NO",
                      cicub: "0.00",
                      ciodb: "0.00",
                      cilastamtpd: "26.86",
                      cilastpaydt: "27/12/2022",
                      ciasofdt: "22/11/2022",
                      cinxtdudt: "",
                      cisummry: "C0000000F00FF00000FFF00F",
                    },
                    {
                      cicrdtr: "UTIL",
                      ciprd: "MBL",
                      ciaccno: "5183652631",
                      cilimit: "350.00",
                      ciissudt: "25/07/2021",
                      ciprodexpdt: "",
                      cistatus: "S",
                      ciclsddt: "",
                      citnr: "0",
                      cifrq: "M",
                      ciinstl: "0.00",
                      cisal: "N",
                      cisec: "NO",
                      cicub: "350.71",
                      ciodb: "350.71",
                      cilastamtpd: "339.28",
                      cilastpaydt: "25/09/2022",
                      ciasofdt: "16/10/2022",
                      cinxtdudt: "",
                      cisummry: "RRRRRRR6543210FFF0FFFFF0",
                    },
                    {
                      cicrdtr: "TABY",
                      ciprd: "BNPL",
                      ciaccno: "F26C6D697E80417882AC",
                      cilimit: "142.00",
                      ciissudt: "27/04/2022",
                      ciprodexpdt: "27/07/2022",
                      cistatus: "C",
                      ciclsddt: "25/05/2022",
                      citnr: "3",
                      cifrq: "M",
                      ciinstl: "47.25",
                      cisal: "N",
                      cisec: "NO",
                      cicub: "0.00",
                      ciodb: "0.00",
                      cilastamtpd: "47.25",
                      cilastpaydt: "25/05/2022",
                      ciasofdt: "25/05/2022",
                      cinxtdudt: "",
                      cisummry: "C0N",
                    },
                    {
                      cicrdtr: "ECFF",
                      ciprd: "PLN",
                      ciaccno: "5737460",
                      cilimit: "16700.00",
                      ciissudt: "22/07/2022",
                      ciprodexpdt: "27/07/2024",
                      cistatus: "W",
                      ciclsddt: "26/04/2023",
                      citnr: "24",
                      cifrq: "M",
                      ciinstl: "1113.19",
                      cisal: "N",
                      cisec: "NO",
                      cicub: "24490.28",
                      ciodb: "6679.14",
                      cilastamtpd: "0.00",
                      cilastpaydt: "",
                      ciasofdt: "26/04/2023",
                      cinxtdudt: "",
                      cisummry: "W55421000D",
                    },
                    {
                      cicrdtr: "TABY",
                      ciprd: "BNPL",
                      ciaccno: "A2720E0AE45443BEAFA9",
                      cilimit: "475.00",
                      ciissudt: "30/04/2022",
                      ciprodexpdt: "30/07/2022",
                      cistatus: "C",
                      ciclsddt: "22/07/2022",
                      citnr: "3",
                      cifrq: "M",
                      ciinstl: "158.44",
                      cisal: "N",
                      cisec: "NO",
                      cicub: "0.00",
                      ciodb: "0.00",
                      cilastamtpd: "158.44",
                      cilastpaydt: "22/07/2022",
                      ciasofdt: "22/07/2022",
                      cinxtdudt: "",
                      cisummry: "CMM",
                    },
                    {
                      cicrdtr: "MALM",
                      ciprd: "CDL",
                      ciaccno: "MURRRIYADH61016",
                      cilimit: "10000.00",
                      ciissudt: "30/07/2022",
                      ciprodexpdt: "01/08/2025",
                      cistatus: "W",
                      ciclsddt: "02/05/2023",
                      citnr: "36",
                      cifrq: "M",
                      ciinstl: "461.00",
                      cisal: "N",
                      cisec: "NO",
                      cicub: "15678.00",
                      ciodb: "3227.00",
                      cilastamtpd: "461.00",
                      cilastpaydt: "06/12/2022",
                      ciasofdt: "02/05/2023",
                      cinxtdudt: "",
                      cisummry: "W65442210DD",
                    },
                    {
                      cicrdtr: "ZANP",
                      ciprd: "PLN",
                      ciaccno: "C7872E19-D2B3-488F-85A8-4E2F85A65885",
                      cilimit: "4968.00",
                      ciissudt: "10/08/2022",
                      ciprodexpdt: "01/02/2024",
                      cistatus: "A",
                      ciclsddt: "",
                      citnr: "18",
                      cifrq: "M",
                      ciinstl: "491.28",
                      cisal: "N",
                      cisec: "OT",
                      cicub: "8351.76",
                      ciodb: "5895.36",
                      cilastamtpd: "491.28",
                      cilastpaydt: "",
                      ciasofdt: "10/08/2022",
                      cinxtdudt: "",
                      cisummry: "666666MMDD432110N",
                    },
                    {
                      cicrdtr: "TABY",
                      ciprd: "BNPL",
                      ciaccno: "E4BFC7C1562B4F92B351",
                      cilimit: "299.00",
                      ciissudt: "26/09/2022",
                      ciprodexpdt: "26/12/2022",
                      cistatus: "S",
                      ciclsddt: "",
                      citnr: "4",
                      cifrq: "M",
                      ciinstl: "100.00",
                      cisal: "N",
                      cisec: "NO",
                      cicub: "99.75",
                      ciodb: "99.75",
                      cilastamtpd: "99.75",
                      cilastpaydt: "11/10/2022",
                      ciasofdt: "11/10/2022",
                      cinxtdudt: "",
                      cisummry: "6666666654320000",
                    },
                    {
                      cicrdtr: "TABY",
                      ciprd: "BNPL",
                      ciaccno: "A3E9740690334A10BFD9",
                      cilimit: "412.00",
                      ciissudt: "26/09/2022",
                      ciprodexpdt: "26/12/2022",
                      cistatus: "S",
                      ciclsddt: "",
                      citnr: "4",
                      cifrq: "M",
                      ciinstl: "137.00",
                      cisal: "N",
                      cisec: "NO",
                      cicub: "411.75",
                      ciodb: "411.75",
                      cilastamtpd: "137.25",
                      cilastpaydt: "26/09/2022",
                      ciasofdt: "26/09/2022",
                      cinxtdudt: "",
                      cisummry: "6666666666543200",
                    },
                    {
                      cicrdtr: "TABY",
                      ciprd: "BNPL",
                      ciaccno: "61F0958C98D24C5EBF87",
                      cilimit: "149.00",
                      ciissudt: "26/09/2022",
                      ciprodexpdt: "26/12/2022",
                      cistatus: "C",
                      ciclsddt: "11/10/2022",
                      citnr: "4",
                      cifrq: "M",
                      ciinstl: "50.00",
                      cisal: "N",
                      cisec: "NO",
                      cicub: "0.00",
                      ciodb: "0.00",
                      cilastamtpd: "49.75",
                      cilastpaydt: "11/10/2022",
                      ciasofdt: "11/10/2022",
                      cinxtdudt: "",
                      cisummry: "C0",
                    },
                    {
                      cicrdtr: "UTIL",
                      ciprd: "MBL",
                      ciaccno: "1008789370_557459288",
                      cilimit: "900.00",
                      ciissudt: "02/10/2022",
                      ciprodexpdt: "",
                      cistatus: "A",
                      ciclsddt: "",
                      citnr: "0",
                      cifrq: "M",
                      ciinstl: "0.00",
                      cisal: "N",
                      cisec: "NO",
                      cicub: "1100.60",
                      ciodb: "468.10",
                      cilastamtpd: "6.00",
                      cilastpaydt: "04/12/2023",
                      ciasofdt: "05/12/2023",
                      cinxtdudt: "",
                      cisummry: "1000010000010M0",
                    },
                    {
                      cicrdtr: "UTIL",
                      ciprd: "NET",
                      ciaccno: "1008789370_831038756724",
                      cilimit: "50.00",
                      ciissudt: "11/05/2017",
                      ciprodexpdt: "",
                      cistatus: "S",
                      ciclsddt: "",
                      citnr: "0",
                      cifrq: "M",
                      ciinstl: "0.00",
                      cisal: "N",
                      cisec: "NO",
                      cicub: "385.91",
                      ciodb: "385.91",
                      cilastamtpd: "160.05",
                      cilastpaydt: "28/10/2018",
                      ciasofdt: "05/12/2023",
                      cinxtdudt: "",
                      cisummry: "RRRRRRRRRRRR654321000000",
                    },
                  ],
                  cimsg: null,
                },
                defaults: {
                  default: [
                    {
                      dfprd: "VIN",
                      dfcapl: "P",
                      dfaccno: "D3364728",
                      dfcrdtr: "TMWL",
                      dfloaddt: "23/06/2014",
                      dforigamt: "74605.00",
                      dfcub: "0.00",
                      dfstat: "FS",
                      dfsettlddate: "27/02/2019",
                    },
                    {
                      dfprd: "CRC",
                      dfcapl: "P",
                      dfaccno: "5691047437",
                      dfcrdtr: "NCBB",
                      dfloaddt: "16/03/2015",
                      dforigamt: "4525.40",
                      dfcub: "0.00",
                      dfstat: "FS",
                      dfsettlddate: "26/03/2021",
                    },
                    {
                      dfprd: "LND",
                      dfcapl: "P",
                      dfaccno: "2055585965.20171023",
                      dfcrdtr: "STC",
                      dfloaddt: "20/09/2019",
                      dforigamt: "1324.21",
                      dfcub: "0.00",
                      dfstat: "FS",
                      dfsettlddate: "25/03/2020",
                    },
                    {
                      dfprd: "MBL",
                      dfcapl: "P",
                      dfaccno: "5140243436",
                      dfcrdtr: "STC",
                      dfloaddt: "05/01/2022",
                      dforigamt: "7250.08",
                      dfcub: "7150.00",
                      dfstat: "PP",
                      dfsettlddate: "",
                    },
                    {
                      dfprd: "MBL",
                      dfcapl: "P",
                      dfaccno: "1000129850168744",
                      dfcrdtr: "MBLY",
                      dfloaddt: "10/12/2020",
                      dforigamt: "1104.08",
                      dfcub: "1104.08",
                      dfstat: "OS",
                      dfsettlddate: "",
                    },
                    {
                      dfprd: "LND",
                      dfcapl: "P",
                      dfaccno: "1000139817765864",
                      dfcrdtr: "MBLY",
                      dfloaddt: "10/12/2020",
                      dforigamt: "1108.57",
                      dfcub: "1108.57",
                      dfstat: "OS",
                      dfsettlddate: "",
                    },
                    {
                      dfprd: "LND",
                      dfcapl: "P",
                      dfaccno: "1000133012272006",
                      dfcrdtr: "MBLY",
                      dfloaddt: "11/12/2020",
                      dforigamt: "1193.51",
                      dfcub: "1193.51",
                      dfstat: "OS",
                      dfsettlddate: "",
                    },
                    {
                      dfprd: "LND",
                      dfcapl: "P",
                      dfaccno: "1000145564273476",
                      dfcrdtr: "MBLY",
                      dfloaddt: "11/12/2020",
                      dforigamt: "889.11",
                      dfcub: "889.11",
                      dfstat: "OS",
                      dfsettlddate: "",
                    },
                    {
                      dfprd: "LND",
                      dfcapl: "P",
                      dfaccno: "1000131021977850",
                      dfcrdtr: "MBLY",
                      dfloaddt: "11/12/2020",
                      dforigamt: "806.67",
                      dfcub: "806.67",
                      dfstat: "OS",
                      dfsettlddate: "",
                    },
                    {
                      dfprd: "PLN",
                      dfcapl: "P",
                      dfaccno: "5737460",
                      dfcrdtr: "ECFF",
                      dfloaddt: "26/04/2023",
                      dforigamt: "24490.28",
                      dfcub: "24490.28",
                      dfstat: "OS",
                      dfsettlddate: "",
                    },
                    {
                      dfprd: "CDL",
                      dfcapl: "P",
                      dfaccno: "MURRRIYADH61016",
                      dfcrdtr: "MALM",
                      dfloaddt: "02/05/2023",
                      dforigamt: "15678.00",
                      dfcub: "16139.00",
                      dfstat: "OS",
                      dfsettlddate: "",
                    },
                  ],
                },
                bouncedchecks: null,
                publicnotices: null,
                judgements: {
                  judgement: [
                    {
                      ejenforcedate: "11/04/2023",
                      ejresnumber: "3231841005",
                      ejexectype: "EXE02",
                      ejcity: "ABH",
                      ejcourtcode: "CE999",
                      ejcasenumber: "3231841005_1076044229_230412052528889",
                      ejdateloaded: "12/04/2023",
                      ejorigclaimamt: "8,352.00",
                      ejclaimamt: "8,352.00",
                      ejstatus: "NOTEX",
                      ejsettledate: "",
                    },
                    {
                      ejenforcedate: "27/02/2023",
                      ejresnumber: "2819453005",
                      ejexectype: "EXE02",
                      ejcity: "KHA",
                      ejcourtcode: "CE001",
                      ejcasenumber: "2819453005_1076044229_230228101750850",
                      ejdateloaded: "28/02/2023",
                      ejorigclaimamt: "24,490.00",
                      ejclaimamt: "24,490.00",
                      ejstatus: "NOTEX",
                      ejsettledate: "",
                    },
                    {
                      ejenforcedate: "14/02/2023",
                      ejresnumber: "2692481005",
                      ejexectype: "EXE02",
                      ejcity: "ABH",
                      ejcourtcode: "CE999",
                      ejcasenumber: "2692481005_1076044229_230214093310171",
                      ejdateloaded: "14/02/2023",
                      ejorigclaimamt: "15,678.00",
                      ejclaimamt: "15,678.00",
                      ejstatus: "NOTEX",
                      ejsettledate: "",
                    },
                    {
                      ejenforcedate: "07/06/2017",
                      ejresnumber: "38683163",
                      ejexectype: "EXE02",
                      ejcity: "UNK",
                      ejcourtcode: "CE005",
                      ejcasenumber: "38683163_1076044229_171126104046483",
                      ejdateloaded: "26/11/2017",
                      ejorigclaimamt: "42,300.00",
                      ejclaimamt: "0.00",
                      ejstatus: "EXETD",
                      ejsettledate: "11/03/2019",
                    },
                  ],
                },
                narratives: null,
                addresses: {
                  address: [
                    {
                      caloaddt: "05/10/2022",
                      cacadt: "POST",
                      cacad1A: null,
                      cacad2A: null,
                      cacad1E: "EASTERN REGION",
                      cacad2E: null,
                      cacad6: "00000",
                      cacad7: "32257",
                      cacad8A: {
                        value: "الدمام",
                        lang: "ar",
                      },
                      cacad8E: "Dammam",
                      cacad9: "SAU",
                    },
                    {
                      caloaddt: "08/08/2022",
                      cacadt: "POST",
                      cacad1A: null,
                      cacad2A: null,
                      cacad1E: "8663",
                      cacad2E: null,
                      cacad6: "NATAD",
                      cacad7: "32511",
                      cacad8A: null,
                      cacad8E: "??????",
                      cacad9: "SAU",
                    },
                    {
                      caloaddt: "29/07/2022",
                      cacadt: "RESID",
                      cacad1A: {
                        value: "الرياض",
                        lang: "ar",
                      },
                      cacad2A: {
                        value: "الرياض",
                        lang: "ar",
                      },
                      cacad1E: null,
                      cacad2E: null,
                      cacad6: null,
                      cacad7: "32515",
                      cacad8A: {
                        value: "الرياض",
                        lang: "ar",
                      },
                      cacad8E: null,
                      cacad9: "SAU",
                    },
                  ],
                },
                contacts: {
                  ccnt: [
                    {
                      ccn1: "M",
                      ccn2: "966",
                      ccn3: "",
                      ccn4: "557459288",
                      ccn5: "",
                    },
                    {
                      ccn1: "M",
                      ccn2: "966",
                      ccn3: "2050",
                      ccn4: "0557459288",
                      ccn5: "",
                    },
                    {
                      ccn1: "M",
                      ccn2: "966",
                      ccn3: "50",
                      ccn4: "0500751048",
                      ccn5: "",
                    },
                    {
                      ccn1: "M",
                      ccn2: "966",
                      ccn3: "96",
                      ccn4: "6500751048",
                      ccn5: "",
                    },
                    {
                      ccn1: "M",
                      ccn2: "966",
                      ccn3: "65",
                      ccn4: "966500751048",
                      ccn5: "123",
                    },
                    {
                      ccn1: "M",
                      ccn2: "966",
                      ccn3: "",
                      ccn4: "500751048",
                      ccn5: "",
                    },
                    {
                      ccn1: "O",
                      ccn2: "966",
                      ccn3: "0",
                      ccn4: "0",
                      ccn5: "",
                    },
                    {
                      ccn1: "M",
                      ccn2: "0009",
                      ccn3: "0",
                      ccn4: "0544927787",
                      ccn5: "",
                    },
                    {
                      ccn1: "H",
                      ccn2: "966",
                      ccn3: "0",
                      ccn4: "0",
                      ccn5: "",
                    },
                    {
                      ccn1: "M",
                      ccn2: "966",
                      ccn3: "04",
                      ccn4: "532566004",
                      ccn5: "",
                    },
                    {
                      ccn1: "M",
                      ccn2: "966",
                      ccn3: "50",
                      ccn4: "0532566004",
                      ccn5: "",
                    },
                    {
                      ccn1: "M",
                      ccn2: "966",
                      ccn3: "0",
                      ccn4: "0541162164",
                      ccn5: "",
                    },
                    {
                      ccn1: "M",
                      ccn2: "100",
                      ccn3: "01",
                      ccn4: "27832628043",
                      ccn5: "",
                    },
                    {
                      ccn1: "M",
                      ccn2: "966",
                      ccn3: "000",
                      ccn4: "966532566004",
                      ccn5: "",
                    },
                    {
                      ccn1: "M",
                      ccn2: "966",
                      ccn3: "000",
                      ccn4: "966544927787",
                      ccn5: "",
                    },
                    {
                      ccn1: "M",
                      ccn2: "966",
                      ccn3: "56",
                      ccn4: "0946660",
                      ccn5: "",
                    },
                    {
                      ccn1: "M",
                      ccn2: "966",
                      ccn3: "05",
                      ccn4: "60946660",
                      ccn5: "",
                    },
                    {
                      ccn1: "O",
                      ccn2: "966",
                      ccn3: "03",
                      ccn4: "8090583",
                      ccn5: "",
                    },
                    {
                      ccn1: "H",
                      ccn2: "966",
                      ccn3: "03",
                      ccn4: "8094433",
                      ccn5: "",
                    },
                    {
                      ccn1: "H",
                      ccn2: "966",
                      ccn3: "00",
                      ccn4: "0000000",
                      ccn5: "",
                    },
                    {
                      ccn1: "H",
                      ccn2: "966",
                      ccn3: "03",
                      ccn4: "8905102",
                      ccn5: "",
                    },
                  ],
                },
                employers: {
                  employer: [
                    {
                      etyp: "C",
                      enme: "???? ?????? ???????? ?????????",
                      enma: null,
                      eadr: [
                        {
                          eadt: "POST",
                          ead1A: null,
                          ead2A: null,
                          ead1E: null,
                          ead2E: null,
                          ead6: "999",
                          ead7: "11492",
                          ead8A: {
                            value: "???? ???????",
                            lang: "ar",
                          },
                          ead8E: "ADDRESS",
                          ead9: "SAU",
                        },
                      ],
                      eoca: null,
                      eoce: "N/A",
                      edoe: "01/04/2020",
                      elen: "44",
                      ecex: "",
                      edld: "24/12/2023",
                      embs: "3000.00",
                      etms: "5000.00",
                    },
                    {
                      etyp: "C",
                      enme: null,
                      enma: null,
                      eadr: [
                        {
                          eadt: "",
                          ead1A: null,
                          ead2A: null,
                          ead1E: null,
                          ead2E: null,
                          ead6: null,
                          ead7: null,
                          ead8A: null,
                          ead8E: null,
                          ead9: null,
                        },
                      ],
                      eoca: null,
                      eoce: "OTHERS",
                      edoe: "",
                      elen: "0",
                      ecex: "",
                      edld: "10/11/2022",
                      embs: "0.00",
                      etms: "0.00",
                    },
                    {
                      etyp: "C",
                      enme: null,
                      enma: {
                        value: "شركة القرية الاوربية للمقاولات",
                        lang: "ar",
                      },
                      eadr: [
                        {
                          eadt: "WORK",
                          ead1A: null,
                          ead2A: null,
                          ead1E: "RIYADH CITY  KINGDOM OF SAUDI ARABIA 11111",
                          ead2E: null,
                          ead6: "6316",
                          ead7: "11111",
                          ead8A: {
                            value: "الرياض",
                            lang: "ar",
                          },
                          ead8E: "Riyadh",
                          ead9: "SAU",
                        },
                      ],
                      eoca: null,
                      eoce: "EMPLOYED",
                      edoe: "",
                      elen: "31",
                      ecex: "",
                      edld: "30/10/2022",
                      embs: "4140.00",
                      etms: "4140.00",
                    },
                  ],
                },
                advisorysummarytext: null,
                summary: {
                  cntpe: "25",
                  cntmtde: "0",
                  cntci: "7",
                  cntgci: "0",
                  cntdef: "11",
                  eiid: "11/03/2010",
                  totlim: "7179.00",
                  totglim: "0.00",
                  totliab: "10941.46",
                  totgliab: "0.00",
                  totdef: "181494.91",
                  curdb: "101401.22",
                },
                score: {
                  scscore: "422",
                  screasoncodes: {
                    screasoncode: ["D2", "D6", "X4", "M1"],
                  },
                  scscorecard: "6",
                  scscoreindex: "1",
                  scminimum: "300",
                  scmaximum: "850",
                  scerror: null,
                },
              },
            ],
            disclaimer: {
              ditext:
                "This information has been collated from various sources on a confidential basis and doesn't represent the opinion of Saudi Credit Bureau (SIMAH). No Liability (in contract or otherwise whatsoever) attaches to SIMAH as a result of taking any investment and/or any other decision based on information provided. Disclosure: SIMAH, a Closed Joint Stock Company, Capital SR 400,000,000 Paid in Full- C.R 1010171047-Membership No.115731-,Toll Free No. 8003010046, Fax No. 966112188797+ P.O Box 8859 Riyadh 11492- National Address: Riyadh, Al Shuhada, Building No. 2596, Unit No. 1, Additional No.7347, Zip Code 13241. Under the Supervision and Regulation of SAMA with a License No. 2/37. www.simah.com",
              ditextar: {
                value:
                  "لقد تم تجميع هذه المعلومات من مصادر مختلفة على أساس السرية والخصوصية وهي لا تمثل رأي الشركة السعودية للمعلومات الائتمانية (سمة) ولا يلحق سمة أي مسؤولية قانونية نتيجة اتخاذ أي قرار استثماري أو غيره بناءً على المعلومات الواردة. الإفصاح: سمة، شركة مساهمة مقفلة، رأس مال 400.000.000 ريال مدفوع بالكامل، رقم السجل التجاري 1010171047، عضوية رقم 115731، الهاتف المجاني: 8003010046، رقم الفاكس: 966112188797+ ص.ب. 8859 الرياض 11492، العنوان الوطني: الرياض-حي الشهداء مبنى رقم: 2596، رقم الوحدة:1، الرقم الإضافي:7347، الرمز البريدي:13241. خاضعة لإشراف ورقابة البنك المركزي السعودي بموجب قرار الترخيص رقم 2/ 37. www.simah.com",
                lang: "ar",
              },
            },
          },
          error: [],
          noerrors: null,
          seq: null,
        },
      ],
      parser: null,
    },
  },
  errorResponse: null,
  responseXml: "",
  valid: true,
};
